#include "auto/schismico_hires.h"

/* XPM */
const char *_schism_icon_xpm_hires[] = {
/* columns rows colors chars-per-pixel */
"128 128 230 2 ",
"   c None",
".  c #050505",
"X  c #0B0B0B",
"o  c #110F11",
"O  c #151315",
"+  c #191719",
"@  c #1C1B1C",
"#  c #191717",
"$  c #211E1E",
"%  c #1B251D",
"&  c #25211F",
"*  c #211F21",
"=  c #242324",
"-  c #292525",
";  c #292729",
":  c #2C2B2C",
">  c #2A2A26",
",  c #312D2C",
"<  c #352D27",
"1  c #283829",
"2  c #34312E",
"3  c #3B322C",
"4  c #302F30",
"5  c #343334",
"6  c #3A3534",
"7  c #3C3936",
"8  c #383638",
"9  c #3C3B3C",
"0  c #343D34",
"q  c #2F3A30",
"w  c #1F2B20",
"e  c #433A34",
"r  c #423D3B",
"t  c #483C38",
"y  c #42382F",
"u  c #29452C",
"i  c #384837",
"p  c #375839",
"a  c #2F4E31",
"s  c #35643A",
"d  c #39663C",
"f  c #39683E",
"g  c #336237",
"h  c #44413E",
"j  c #4C423C",
"k  c #464B38",
"l  c #51453E",
"z  c #584A3E",
"x  c #45533D",
"c  c #50543F",
"v  c #65603B",
"b  c #413F41",
"n  c #3D5641",
"m  c #3C6A40",
"M  c #3E6341",
"N  c #444344",
"B  c #494543",
"V  c #4C4945",
"C  c #494749",
"Z  c #4D4B4B",
"A  c #454B45",
"S  c #534541",
"D  c #544A44",
"F  c #5A4C45",
"G  c #524D4C",
"H  c #5A4E49",
"J  c #594441",
"K  c #435442",
"L  c #4C5C4C",
"P  c #485847",
"I  c #54514E",
"U  c #5C524C",
"Y  c #595848",
"T  c #514F51",
"R  c #545354",
"E  c #595654",
"W  c #555A54",
"Q  c #5C5A56",
"!  c #5D5B5A",
"~  c #595758",
"^  c #664D4A",
"/  c #63544C",
"(  c #6A534C",
")  c #6B5A4E",
"_  c #64574B",
"`  c #635652",
"'  c #6C5653",
"]  c #655B55",
"[  c #6B5C53",
"{  c #625E5C",
"}  c #695E59",
"|  c #735C58",
" . c #795E4F",
".. c #426E46",
"X. c #436E48",
"o. c #49664A",
"O. c #46724A",
"+. c #49744C",
"@. c #467448",
"#. c #536353",
"$. c #596958",
"%. c #4E7952",
"&. c #4E7252",
"*. c #527B55",
"=. c #557D58",
"-. c #58775A",
";. c #526D4E",
":. c #797549",
">. c #6C6155",
",. c #63615E",
"<. c #6C625C",
"1. c #636B5D",
"2. c #686858",
"3. c #736155",
"4. c #73655C",
"5. c #75695D",
"6. c #7B6A5D",
"7. c #796757",
"8. c #7D725A",
"9. c #6E6A4A",
"0. c #666462",
"q. c #6B6663",
"w. c #6B6965",
"e. c #6D6C6A",
"r. c #646E61",
"t. c #736661",
"y. c #746A64",
"u. c #7B6C64",
"i. c #736D6B",
"p. c #7A6D69",
"a. c #7C6663",
"s. c #657763",
"d. c #7D7166",
"f. c #73726C",
"g. c #7C736C",
"h. c #78786B",
"j. c #747372",
"k. c #7E7671",
"l. c #7F7873",
"z. c #7B7B7B",
"x. c #5E7660",
"c. c #846A5A",
"v. c #837A56",
"b. c #836E65",
"n. c #847265",
"m. c #8B7465",
"M. c #82756C",
"N. c #84796D",
"B. c #8C7A6C",
"V. c #8A7968",
"C. c #937C6C",
"Z. c #937767",
"A. c #827A74",
"S. c #8B7D73",
"D. c #887673",
"F. c #937F73",
"G. c #5C835E",
"H. c #578057",
"J. c #62865D",
"K. c #5D8361",
"L. c #5F8861",
"P. c #638964",
"I. c #678B6A",
"U. c #698C6C",
"Y. c #658567",
"T. c #6C916D",
"R. c #769775",
"E. c #6F8E6F",
"W. c #88874A",
"Q. c #92914F",
"!. c #B1B153",
"~. c #8D886B",
"^. c #96846D",
"/. c #8D827A",
"(. c #8D8176",
"). c #948275",
"_. c #9B8474",
"`. c #93857B",
"'. c #9A8679",
"]. c #9B8A7C",
"[. c #958A79",
"{. c #95986B",
"}. c #A1846F",
"|. c #A48975",
" X c #A48C7B",
".X c #A98E7A",
"XX c #A38772",
"oX c #AB917D",
"OX c #A6907D",
"+X c #B5957E",
"@X c #A6A56B",
"#X c #B8B872",
"$X c #C2C259",
"%X c #CCCC63",
"&X c #C6C676",
"*X c #D4D47A",
"=X c #D1D177",
"-X c #968A82",
";X c #9B8D83",
":X c #948780",
">X c #9E9086",
",X c #9F9188",
"<X c #A18F82",
"1X c #A49284",
"2X c #AB9584",
"3X c #A3948A",
"4X c #AC9A8C",
"5X c #A9988A",
"6X c #B59780",
"7X c #B69982",
"8X c #B99B85",
"9X c #B39C8B",
"0X c #BB9E89",
"qX c #B19E91",
"wX c #AD9D91",
"eX c #BDA28D",
"rX c #B4A193",
"tX c #BEA592",
"yX c #BDA99A",
"uX c #BBA798",
"iX c #C0A693",
"pX c #C2A996",
"aX c #C5AD9B",
"sX c #C7B09F",
"dX c #C8B19F",
"fX c #CAB4A3",
"gX c #CCB7A8",
"hX c #CDB8A8",
"jX c #C7B2A2",
"kX c #C3AFA0",
/* pixels */
"                                                                                                                                                                                                                                                                ",
"                                                                                                                                                                                                                                                                ",
"                                                                                                                                                                                                                                                                ",
"                                                                                                                                                                                                                                                                ",
"                                                                                                                                                                                                                                                                ",
"                                                                                                                                                                                                                                                                ",
"                                                                                                                                                                                                                                                                ",
"                                                                                                                                                                                                                                                                ",
"                                                                                                                                                                                        e <                                                                     ",
"                                                                                                                                                                                    l m.8X3.                                                                    ",
"                                                                                                                                                                              < ^ |.0X8X8XoX>         9                                                         ",
"                                                                                                                                                                          e 3.7X0X0X8X8X8X0Xj     b b i                                                         ",
"                                                                                                                                                                      l Z.0X8X0X0X0X8X8X8X8X3.r N N 9 9 9                                                       ",
"                                                                                                                                                                2 / oX0X0X0X0X0X8XOX) F 8X8XoX2 N N b b 9                                                       ",
"                                                                                                                                                            t 7.8X0X0X0X0X0X8XC.F - @ e 8X8X0Xj N 9 b 9 9                                                       ",
"                                                                                                                                                        D C.eXeX0X0X0X0X7X7.e $ * z V.0X7X0X7X[ 9 n 9 b 9 8                                                     ",
"                                                                                                                                                  3 ` b._ 7XeXeX8XeX^.:.k $ < ) oX8X8X8X8X8X8XoX2 b b 9 9 8                                                     ",
"                                                                                                                                              j 3.6.Y H D V.8XeX:.:.!.!.v c.8X8X8X0X0X8X8X8X8X8Xj b b 9 9 9                                                     ",
"                                                                                                                                          F 6.4.H H z  .B.oX:.W.$XQ.:.Z.8XeX8X0X7X8X8X0X8X8X8X8X[ 9 b 9 9 8 8                                                   ",
"                                                                                                                                    6 ) n.[ H U U 7.|.Z.:.Q.!.W.:.oX8X8X8XeXc.^ ) |.7.F 8X8X8X8X.X2 n 9 9 0 8                                                   ",
"                                                                                                                                j 6.u./ Y U _ n.7X7.J.!.!.:.v.eX0XeXeX.X3.D l l l j l D .X8X8X8X8Xj r 9 9 8 0                                                   ",
"                                                                                                                            U n.5.U U U 4.F. X9.W.$XQ.:._.0X0XeX0XV.) l z D l D l ) V.7Xn.U |.8X8X) 9 9 9 9 8 5                                                 ",
"                                                                                                                      y [ M.} Y U ] u.2XV.:.!.!.v.:.0XeX0X0X6Xu.U V D D D l F 5.OX|.3.z j j 3.8X8X.X2 9 9 0 5 5                                                 ",
"                                                                                                                  j u.M.] ` / >.V.9X9.W.$XQ.:.C.eXeX0XeX_.>.D D D z z V ) V.8XV._ j l j _ m.7X7X8X8Xt i 9 8 8 8                                                 ",
"                                                                                                              U V.u.Y ` ] 5.'._.9.Q.$XW.:.7XtXtX0X0Xn.] D D F D D H 4..XoX6.F S l D 3. X8X8X8X8X8X8X[ 7 9 7 8 5 5                                               ",
"                                                                                                        e <.B.5.` Q } n.9Xd.:.!.!.v.V.eXeXiXeX0X4.H H H H H D [ V.0X0X^.l D l _ m.8X8X8X8X8X0X7X8X8XoX< 9 9 5 5 5                                               ",
"                                                                                                    D u.M.} ] ` 4.).OX8.W.$X%Xv..XiXeXiXeXeXeXeXH H H H U 4. XeX0X0X0X7XD 7.|.8X0X8X0X8X8X8X8X8X8X8X7Xt 9 8 5 5 4                                               ",
"                                                                                                / B.d.] } ] d.1X(.U Q.%X%X%X%X:.eXiXeXeXeXeXeXeX` D [ V.0XoX|.0X0X0X0X0X8X0X0X0X0X8X8X8X8X8X8X8X7X7X8X) 5 9 0 5 5 5                                             ",
"                                                                                          e 4.S.y.] ] <.B.eXV.W.Q.k _ k !.W.8.eXeXeXtXeXiXeXeXiXV.OXeXV.} D 4.eX0X0X0X0X0X0X0X8X0X8X8X8X8X8X8X7X8X+X8X.X2 8 0 5 q 4                                             ",
"                                                                                      D M.N.<.} } u.].].u.).W.%X%X%Xv >.'.tXeXiXiXiXeXeXeXeXeXiX6X6.Y F D 3._.eXeX0X0X0X0X0X0X8X0X8X0X8X8X8X8X8X8X8X8X7Xh 7 8 5 4 4                                             ",
"                                                                                  ` ).g.} <.<.V.2XB.<.] } S.d.%XQ.v.rXtXpXtXiXtXeXiXeXiXiXeXiXeX_.D ` n.6X0XeX0X0X0XeX0X0X8X0X0X8X8X8X8X8X8X8X8X8X8X8X7X) 5 5 5 5 4 :                                           ",
"                                                                            h 5.).u.,.>.y.`.2XM.>.,.} ] ] M.N.%XV.iXiXtX Xn.eXiXiXeXeXeXeXeXeXeXeX_.eXeXeXeX0XeX0X0X0X0X0X0X8X8XC.OX0X8X8X8X8X8X8X+X8X7X.X: 0 5 4 5 4                                           ",
"                                                                        H B.S.q.<.<.M.1X].u.} } } ] ] ] } y.2X:.].eXV.>.` Y iXtXiX0X0XiXiXeXiX0XeXeXeX0X0XeX0X0X0X0X8X8X8XXXc. .c._ c Y eX+XeX+X8X8X+X8X+Xt 6 5 4 4 4                                           ",
"                                                                  3 ] `.N.<.<.t.(.9X(.4.<.} } } <.] } ] ] ).iX].u.] ] U >.B.iXiXiXiXiXeX0XiX0XiXeXeXeXeXeX0XeX0X0X0X7Xm.c.c. .^ k *.H.x +XeX+X+X7X8X8X8X8X) 2 5 4 4 4 4                                         ",
"                                                              j y.[.p.<.<.p.'.aXpXy.<.<.<.,.>.{ ] } } ] <.B.<.] ] ] u.1XiXeXeXiXiX0X0XiXiX0XiX0XeXeXeXeX0XeX0X0XF.m.c.c.( t b  .o.@.@.p +XeX+XeX8X8X8X8X7X.X> 8 5 q 1 :                                         ",
"                                                          U S.(.y.t.<.S.4X4Xy.iX1X5.<.} <.B.t.] } } ] ] ] ] ] 5.B.eXiXtXiXiXiXiXiXiXiX0XiXiX0XiXeXeX0XiX0X2Xm.c.c.c.^ t ( ( t , 1 m m f 8.+XeX+X8X+X8X+X8X7Xe 5 4 4 4 :                                         ",
"                                                    6 } '.A.t.q.p.`.uX'.} N G pX4.,.d.'.pXpXn.<.} ] >.] } n.2XpXiXiXiXiXiXiXiXeXeX0XiX0XeXeXtXeXeXeX0XC.c.c.c.( t ^ ( ^ y - + # & f m m Y 8X8XeX8X8X8X7X+X8X) 2 5 4 4 : :                                       ",
"                                                j n.`.N.t.t.N.<XuXN.E N } ).aXaX(.9XaXpX4XM.<.] <.] y.).tXpXiXiXiXiXiXiXiXiXeXiXiXiXeXiXtXeXeXeX Xm.c.c. .F t ' ^ t < $ @ @ # @ $ p m m x 8X8X+X8X8X+X8X8X+X.X> 4 4 4 : :                                       ",
"                                            Y ).`.f.y.y.(.rX1Xy.C Z y.2XaXaXaXuX).M.].u.] <.} ,.M.2XpXpXpXpXiXpXpXiXiXiXeXiXeXeXtXiXiX0XtXeXeXC.c.c.( l ^ ' J 6 * + $ + $ @ # # $ u m m f ^.8X8X8X+X+X8X+X8X+Xe q : 4 : >                                       ",
"                                      6 <.;X(.y.y.g.;XuX`.{ B E M.uXaXaXaXaXaXM.<.<.,.<.<.d.).iXpXpXpXpXpXtXiX].rXiXiXiXiXiXiXiXeXiX0X Xm._.8X/ J J | ^ t , * * * $ $ $ $ # $ # $ q @.%.@.Y 8X8X8X8X8X8X8X+X8X) 4 4 4 : : >                                     ",
"                                  V M.;XA.y.i.A.5XqXM.I C N N '.aXaXaXaXaXaXaXB.<.<.q.B.4XaXpXpXpXpXpXaX0XS.<.] F.iXiXiXiXiXiXeX7XD.c.c.7.Y D .X/ S 6 ; * * * * * * $ $ @ * - 5 N 7 ....f x 8X8X8X8X8X8X+X8X+X.X< 4 4 : ; ;                                     ",
"                              U `.[.g.p.g.`.uX>Xy.G C C N G d.rXaXaXaXaX'.1XaXS.d.'.pXpXpXpXpXpXpXpX Xd.] ] ] d.9XiXiXeXiXiXF.b.c.c.' J #.J.G.n.S = * = = * * * * * * = 4 t h 5 ; + a f m p OX8X8X+X8X+X8X8X8X+Xe 2 1 : : :                                     ",
"                        e q.1X/.g.y.A.;XrX~.,.Z C C C ,.S.yX;X`.sX4XS.t.<.`.aXpXaXaXaXpXpXpXaXtX(.5.] ] t.).tXiXiXiXeX2XZ.b.m.c.( H | ' P %.@.>.[ = = = * * * * * 4 r B 8 , $ # + + 1 m m m 2.8X8X+X8X+X8X+X8X8X_ : 4 : : = ;                                   ",
"                    D N.>XD.f.g.(.rX1X~.@X*XW.5.T p.1XuX`.p.t.y.d.q.<.S.4XaXaXaXaXpXpXaXpX1XM.} ] } n.2XpXtXtXpX0XF.m.m.c.( F | | H r : 0 +.+.L n.= = = = ; 4 9 S b 4 = @ @ # @ + + * m m m c 8X8X8X8X8X+X8X+X+X.X> 4 : : > ;                                   ",
"                ` 3XqXk.g.A.-XyX^.{.&X=X=X=X@X~.yX5XS.y.y.y.y.q.d.[.aXaXaXaXaXaXaXaXtX).y.>.{ y.).iXpXpXiXiX<Xm.m.m.| ^ ^ t.` b 6 ; : ; 2 O.O.K 6X; = , 7 N N 5 ; $ $ $ @ $ # @ # + # a f f p 8X8X8X8X+X8X+X8X+X+Xe : : : > ; =                                 ",
"          e y.uXgXgXqXS.5X4X~.@X=X*X*X&X{.[.aX;Xg.y.y.y.y.t.D.3XaXaXaXaXaXaXaXaX1XN.<.<.<.B.2XpXpXpXpXpXiX6.Z.b.' F | | H r : : : : ; ; : ..O.o.V.V C V 9 4 * * $ $ $ @ @ @ + @ @ # @ u @.%.O.7.8X+X8X+X8X8X8X+X8X_ : : > > ; %                                 ",
"      D S.jXgXfXfXgXjXuX{.#X*X*X*X*X*X~.sX<Xf.y.y.y.i.p.'.uXaXsXsXaXaXaXaXiX`.u.<.} u.`.pXpXpXpXpX'.C.iX<X( ^ } a.` B 6 : : : : : ; ; ; ; n %.=.u.[ 5 ; * = * * * $ @ $ @ @ @ @ = , 7 k +.@.m P 8X8X+X8X+X8X8X8X+X|.< : : ; = =                                 ",
"  ] 3XgXgXgXfXgXyX:Xk.wX&X*X*X{.#X*X*X[.fX`.y.i.p.A.1XaXaXaXfXaXsXaXaX4XA.5.<.q.B.4XpXaXpXpX9XF.b.Z.[ $.M.u.| D 8 4 4 : 4 4 : : : ; : 5 r o.H.%.Y b.= = = * * * * $ $ $ @ = : 9 h r 5 = s f m p 8X8X8X8X8X+X+X+X8X+Xe : > : ; % =                               ",
"g.hXhXgXgXhXwX:Xg.k.h.rX#X*X&XR @X*X*X{.fX`.p.`.qXfXsXaXfXaXaXaXaX<Xp.<.<.d.].aXaXpXaXiX'.m.m.Z.| Q I.E.6.u.5 5 5 4 4 4 : : 4 : 5 9 V G b 9 +.O.K <X= = = * * * * * * 3 t b b 6 * $ + O u m m s ^.8X+X8X+X8X7X8X8X+X_ : : > = w =                               ",
"A.hXgXjX3XA.k.k.k.k.k.uX#X*X&XR {.*X*X^.fXuXaXjXdXdXsXsXfXaXfXaXaXM.y.S.qXaXaXaXpX5XF.b.C.a.} ' a.] P.=.#.n.4 5 4 4 4 : 4 5 7 V R B 8 : ; : O.+.o._.7 = * * * = : t b b 8 , * + $ + + + w m m f Y 8X8X8X8X+X8X+X+X7XXX> > : = = %                               ",
"N.jX-Xl.A.k.k.k.k.g.j.yX#X*X&XR {.@X~.rXfXsXjXsXdXdXsXsXaXaXfXaXaX9XaXaXaXaXuX).B.Z.m.| ' a.a.H B 5 &.=.L ).5 4 5 , 5 9 C I V 9 , : > ; ; ; M +.O.6.H = = : 7 V b b 4 * $ * + * + + + + % f f f x +X8X+X+X8X8X+X8X+X6X7 > : = = = @                             ",
"A.uXl.A.A.j.k.k.k.k.g.yX#X*X&Xi.).sXfXsXsXfXaXfXdXdXsXsXaXsXaXaXsXaXaXaX2XF.m.C.a.' t.b.} Z 8 8 6 8 L =.*.'.8 5 9 N I G h 8 : : : : ; ; ; * n +.O.Y a.7 B D r 5 ; * * @ $ + + + + + + + # a m ..s +X8X8X+X8X8X+X+X7X6X/ = > = = % =                             ",
"A.yXj./.,X;Xl.k.k.g.g.yX~.^.4XfXfXfXfXdXfXsXsXsXdXdXkXsXaXaXaXaXaXaXaXaXn.n.4.} b.t.T b 9 8 8 8 8 8 P =.=.B.I I E C 9 4 4 : : : : : ; ; ; ; i O.%.Y '.h 8 : $ * * @ * * @ * + + + + # @ - i %.+..._ eX+X+X8X8X8X8X7X+X|.- : = = * *                             ",
"g.jXrXkX`.k.k.A.A.h.A.yXaXfXfXfXdXdXfXfXsXfXsXfXdXdXsXsXfXfXaX1XF.n.'.a.} a.a.` C b 9 8 9 9 8 8 8 5 K G.J.N.<.N 8 4 4 , 4 4 : : : ; : ; : 8 k G.H.o.oX2 = * * * * * * + @ @ + + * ; 6 r h 0 m m d c eX+X8X+X+X+X+X7X+X8X3 > > = = @ *                           ",
"N.gXhXuXA.>XkX3X/.4XfXfXjXfXfXfXfXfXdXdXfXdXsXfXdXdXdXdX9X'.D.F.u.r.E.].a.T N b 9 9 9 8 9 8 7 8 n C W P.G.2.5.4 4 4 4 4 : 4 : : : : 8 h G V i +.+.@.u.D = * * = * @ * @ @ * - y b b e ; $ O p f s p +X+X8X8X8X7X8X+X+X+X_ > = = = @ @                           ",
"k.gXhXgXgXgXgXgXfXhXfXfXfXfXfXfXfXdXfXfXdXdXsXsXdXaX1XF.F.Z.a.t.h.R.U.S.} b b b 9 b 9 9 9 r C W E Z B =.=.#.M.5 4 4 4 : 4 : , 8 N G G h 6 : = K +.@.>.| = * * * * * * ; e b b b < * + + # # u f d s 8.8X+X8X+X7X+X8X+X7XXX= > = % $ @                           ",
"N.gXhXgXgXhXhXfXhXfXhXfXfXfXfXfXfXfXjXdXfXfXjX9X<XF.F.b.q.p.b.<.E P.x.N.y.9 b 9 b 9 b C E ! I N 8 6 4 -.=.L '.5 5 : 4 : 8 r G I C 7 : ; ; ; ; a O.O.F B.= = $ = , 6 b b b < * @ + + + + # # w f d d c +X+X+X+X+X8X+X+X+X+Xy > % = @ @ @                         ",
"g.gXhXgXfXhXfXhXfXfXfXfXfXfXfXfXdXfXfXdXqX<XF.F.m.a.a.D.a.` Z b A P.K.h.N.r 9 b C I { E C b 8 8 8 8 5 o.=.&.].7 4 8 h G I Z r 5 : : : ; ; ; ; q +.O.p 9X, : 5 B b b 3 - @ @ + @ + + + + # # @ d d d x +X+XiXeX+X+X8X+X8X+X_ = = = % @ @                         ",
"N.hXhXgXgXhXfXhXhXfXhXfXfXfXgXgXfXjXjXuXF.F.M.t.D.b.{ T C b N C N G.K.w.(.C R ! ! Z N 9 9 8 8 8 8 8 8 P =.*.B.U Z E I i 8 4 : : : ; : ; ; ; = 4 +.O.O.V.Y C h 2 ; $ $ $ @ @ @ @ # + + + O # O u f m m ^.+X+X+X+X8X+X8X+X+X|.& = % @ @ @                         ",
"g.hXhXgXfXhXhXhXfXhXfXfXfXfXfXqX].F.;Xp.t.p.D.t.~ Z C C C N N b N -.P.s.].,.R C 9 9 9 9 9 9 8 8 8 5 5 K G.L.h.5.C 9 4 4 4 4 : : : : ; ; ; ; > 4 &.=.H.y.4.: @ = * $ @ $ * @ @ + @ + + + + # - h *.H.*.z +XiX+X+X+X7X+X7X+X+X7 & = * % @ @                       ",
"g.gXhXgXgXgXfXgXhXfXgXfXkX1X:XF.S.h.s.rXp.} T C b Z C C b C b C G s.T.s.4XN 9 9 9 r 9 9 9 8 8 8 8 b C #.P.J.2.u.4 4 4 : 4 : : : : : ; ; 5 7 B Z o.%.@.Y n.= * * * @ * @ @ @ @ + + + $ - y ^ ^ ^ %.@.m p +XeX+X+X7X+X7X+X+X+X/ % * % @ @ #                       ",
"g.hXhXgXhXgXgXfXfXfXwX<X'.F.D.a.A.R.E.4X~ Z Z Z Z Z C b C T ~ 0.$.$.L.$.tXC b b 9 9 9 9 9 8 h C ~ ! Z A =.=.W S.5 4 4 , 4 : : : : 4 9 B Z C 7 4 i O.O.k 6X- * * * $ @ $ @ @ @ & , t ^ ^ ^ z y $ p d d p +X+XeX+X7X+X+X7X+X+XXX& = @ @ @ +                       ",
"N.gXgXgXhXhXhXaX3X]. XF.p.k.D.p.1.T.I.3X! Z Z C b Z Z ~ ,.0.~ Z N #.K.-.1XG b 9 b 9 9 h C E ! I C 9 5 8 *.=.L  X4 4 4 4 4 : 5 r C I V 7 4 : ; = 4 @.O.o.).r * * * $ $ & & < t ^ ( ^ b y $ # # O u g s f 9.+X+X+X+X8X+X7X+X8X+X3 = $ @ @ + #                     ",
"g.gXhXgXfXwX<X'.).M.i.D.D.t.~ T W U.U.;X} C C Z ~ ,.q.{ T C b C b W K.K.`.] b 9 N C E ! E C h 8 8 6 5 5 o.=.&.'.r 4 , 5 b C G G r 5 : : : ; = > > O.+.O.5./ * * * & 3 b ^ ' ( J y - + @ # # O O w s f f c eX+X+X7X+X8X+X+X+X+X^ @ % @ @ + +                     ",
"k.gXgXgXjX/.D.p.D.D.i.{ R T T T W U.U.-Xq.R ! e.0.~ Z C b C C b b P K.K.S.q.S R { ~ Z b b 8 8 8 8 8 8 5 L =.=.B.H b S T H b 8 4 : : ; ; ; ; * ; * P +.O._ 6.= 6 t ' ' ' b y * $ + + + + O + O O + s f d p +X7X+X+XeX+X+X+X+X+X|.w % @ # # O                     ",
"k.gXgXwXyXa./.z.e.~ R R R T T T R U.T.-Xl.w.! R C C C C C b C b b P P.P.A.D.{ T b b b 8 8 9 8 8 8 8 5 5 n H.H.g.a.T N 8 4 : : : : : ; ; ; ; ; ; * n O.+.Y .X/ ' ' S e * $ $ + + + + + + + O O O O u f f m 9.8X7X+X+X+X+X+X+X+X+Xy $ @ @ % O #                   ",
"p.5XD.D.wXq.,.R R R R R T T T R #.R.R.`.g.Z C C C C C b C b b C Z ~ T.T.g.B.b 8 b b 8 b 8 9 8 8 8 4 8 b L P.L.2.d.5 4 4 4 4 : : : ; ; ; : ; ; < : B =.J.;. XF 6 - @ @ * $ $ + $ + + + + # O O @ = 0 @.@.@.k +X7X+X+X+X+X+X+X+X+X^ @ $ @ O + #                   ",
"p.l.z.D.wX,.R ~ R R R R R ~ 0.e.0.E.U.(.k.C Z C C C C C C Z R ,.w.~ P.P.w.(.b b b 8 b 8 9 8 8 r b G Q ~ P H.=.W S.4 4 : 4 4 : : : : : ; * , t b | ` J.=.*.b.F * * * * @ $ $ + + $ + + + $ > 5 t r i ....d i 8X7XeX+X+X+X+XeX+X+X}.& % # # # #                   ",
"p.l.A.A.wX{ R ~ R R ! 0.j.e.! R T I.U.z.D.C Z C C C Z R ! 0.{ R C n -.x.2.].9 b r 9 9 9 b b G ~ ! Z b 8 9 *.*.P 1X5 , , , : 4 : : ; 4 t D | ' ' b e X.O.O.) 5.% @ * @ * @ @ @ + + * , 6 r r r , & # a d s p ^.+X+X+X+XeX+XeX+X+X+X3 @ @ # # O O                 ",
"p.A.A.l.5X0.R ~ 0.e.j.0.~ T R T T x.U.l.S.C C T T { q.0.~ T b b b N -.Y.$.rXn 8 9 9 b Z ! ~ G b 9 6 5 5 5 X.=.&.'.r 4 4 , , : 5 b F | | | b t ; - = p O.O.D _.* = @ * @ @ * ; , t t r r , = # o O o u d s s Y +X+XeX+X+X+X+X+X+X+Xz # % # # O O                 ",
"p.l.A.l.5X0.e.j.e.{ R R T T T T Z s.U.h.`.R ! w.q.~ T C b C b C b n #.K.$.rXC C T { { T b b 8 8 8 8 8 5 5 L *.*.N.H 4 : 5 b ^ t.| ' S 8 , * : ; - * i O.O.p 6X2 $ @ = : 8 h j h r : * + + O O + O O % d s s x +X+X+X+X+X+X+X+X+X+X|.& # # # # O                 ",
"p.l.A.A.5X0.0.~ R R R T T T T T T r.E.E.;Xw.! R C C C N C b Z b b N #.K.s.2X} { T b b r b 8 8 8 8 8 8 4 8 K *.=.y.| b / t.| ' S t 4 ; ; ; ; * : - ; q +.X.O.n.D , 7 B B h 7 : = + + @ + + + + o O O O g s s p .X+XeX+X+X+X+X+X+X+X+X3 @ # # O O o               ",
"p.l.A.A.5X0.R ~ R R R T T T T R ! U.R.h.>XZ C C b T b Z b b b b b Z $.T.T.`.0.N 9 b 9 8 9 8 8 8 8 8 5 5 5 A =.G.y.B.6.' S 9 4 : : : : ; ; ; ; - ; * > O.O.+.4.u.B B 6 : = @ # @ # + + + + + O O o o O u s s f _ +X+X+XeX+X+X+X+X+X+Xz @ # # O O o               ",
"i.l.l.A.5Xw.~ R R R R R ~ ! 0.j.0.s.U.e.3XC Z Z Z T Z b b T Z ~ { 0.$.P.K.S.q.9 9 9 8 9 8 9 8 8 8 5 4 r G ` E.U.2.).9 , 4 : : : ; : ; ; ; : = ; ; 4 6 &.H.H.Q ^.: = @ @ @ @ @ + @ + + + O O + + O O O 1 f @.@.i +X+X+X+X+X+X+X+X+X+XXX$ % # O O O               ",
"p.l.A.A.3Xw.R R R ~ ! 0.j.0.,.R Z x.U.s.qXC C C b b Z b ~ { q.,.T C T K.K.N.u.9 9 9 9 9 9 8 8 8 r G ' a.6.] J.=.P 2X8 : : 4 : : : ; > ; ; : 5 7 Z Z Z o.+.O.x 8X: @ * * @ @ @ @ + + # + + O O # * : 6 0 @.@...a +X+X+X+X+X+X+X+X+X+X+X< O O O O o X             ",
"p.l.A.l.3Xe.R ,.0.j.e.0.R T T T T $.U.r.yXT C Z G ~ 0.e.{ R b b b b Z K.K.y.A.b b 9 9 9 9 b T | a.a.' Z 8 5 ;.*.&.).h 4 4 : : : : : : 8 h V V Z r 6 < 0 O.X.m ^.j * @ @ @ $ + @ @ + + + $ - 5 r h e 7 - p d s g 8.eX+X+X+X+XeX+X+X+X+Xc O # # o o X             ",
"p.l.A.A.3Xe.j.e.0.! R T R T T T T $.U.x.yXR E ,.e.{ ~ R b T T b b N A K.G.2.`.9 9 9 b T | b.a.] G 9 5 5 5 5 L *.=.M.U 4 4 : : 5 9 B G G Z r 8 : = = = q O.X.X.5.) @ * @ @ @ @ @ @ = , e r h r 2 = @ O o 1 s s g c +XeX+X+X+X+X+X+X+X+X}.$ # O O o o             ",
"p.l.A.z.wX0.,.~ R R R R T T T T T $.U.s.yXi.,.E R T b b b b b b N b N P.K.1.<XC R | b.b.` G b 8 8 8 8 5 5 5 K *.%.4.>.: 8 r V R G Z 7 5 : = = ; = = = > O.O.X.Y m.@ @ * @ = > 5 r b h r , = @ O O O o O % s s s p +X+X+X+X+X+X+X+X+X+X+X< # O O o o X           ",
"p.l.A.A.3Xe.R R R R R T T T T T ~ s.R.U.qX{ C C T b T b T b b b N b r -.P.2.rXa.a.' G b 8 8 8 8 5 8 5 5 5 5 n =.=.2.M.V R I Z b 5 : : ; ; ; = ; ; = = = p O.X.K 9X= = 2 7 B j h 7 : = # O + O O o O o o o g g g g Z.+X+X+X+X+X+X+X+X+X+Xz # # O o X X           ",
"p.l.A.D.3Xe.~ R R R R R R ! 0.e.w.0.T.Y.3X,.Z C b T b T b b b b b G ' Y.R.s.rXE b b 9 8 9 9 8 8 8 5 5 5 5 8 A K.G.2.'.C r 6 : : : : : ; ; ; ; ; = = = = i X...o.|.U B B h 6 : * + + + + + + O O O o O o o u s g g Y +X+X+X+X+X+X+X+X+X+X^.% O # o X o           ",
"p.l.A.A.3Xi.R ~ R R ! 0.j.e.! R T #.I.I.,X0.Z C C C C C b b R ~ a.b.p.r.P.-.1XR 9 9 9 8 9 8 8 8 8 8 8 h Z E W P.G.L 8X8 : : : : : ; ; ; ; ; ; = = = = : i *.H.=.d.>.5 - $ @ @ @ + + + + # O O O O o o O o w g g s i +X7X+X+X+X+X+X+X+X+X+X< # o o o X X         ",
"i.k.l.A.3Xj.~ ! 0.j.e.,.R T T T T W I.I.-Xe.Z C C C C T { a.D.b.{ T N #.K.K.`.] 9 9 9 9 8 9 8 r C G Q Q I C 9 *.*.X.).B 4 4 : : : : : ; ; ; ; ; 4 7 B V V =.%.+.>.6.* @ @ @ @ + + + + + O + O O O O O o # w ..@.@.p .X+X+X+X+X+X+X+X+X+X+Xz o # o o X X         ",
"y.l.A.A.3Xe.f.f.0.~ R R R T T T T W U.I.:Xp.C Z T } a.D.b.{ R Z b N b W K.K.B.<.9 9 9 9 N C ~ Q ! G N b 8 4 5 o.*.*.M.U , : : : ; ; ; - : 6 9 Z G V C 8 2 ....X.K .X= $ @ @ # @ @ + + # + + O # # @ - 3 y e s ..f d 9.+X8X+X8X+X+X+X+X+X+X}.# # o o X X         ",
"y.l.A.l.3Xe.! R R R R T T T T T T W U.I.:Xl.0.p.D.p.} T Z b b b N N b L K.K.h.d.b C G ~ ! ] G C 9 8 8 5 6 5 4 P *.*.<.4.4 : : : : 5 9 B G G V h 8 : = * = p ..X.p 7X6 @ $ $ + @ + + + # + @ - , r 7 h 7 > & u g g s c +X+X+X+X+X+X+X+X+X+X+X< o o X X X X       ",
"p.l.A.A.3Xg.R ~ R R R T R T T T Z R E.R.-X:Xp.{ T Z Z b Z b Z b b N b P K.K.h.S.{ ,.! G C 9 8 8 8 5 8 5 5 4 5 A *.*.] n.: 5 8 h V I I C r 5 : = * ; * ; * a O.m ..n.H $ + @ + @ @ @ = , 7 h t r 2 = @ O o o % g g g a +X+X+X+X+X+X+X+X+X+X.Xz o O X X X X       ",
"p.l.A.A.,Xg.R ~ R R R R T T T ! q.g.{.R././.C T Z b b Z Z b b b b N B W I.U.h.'.G C 9 9 9 9 8 8 8 8 5 5 5 5 5 i *.*.L ].B I I I B 9 5 : : = = - ; ; ; * * q X.O...>.3.@ $ $ = : 6 h h h 7 : = + O O O o o o o a s g g 8.+X8X+X+X+X+X+X+X+X+X}.# O X X . X       ",
"y.A.A.A.3Xk.R R R R R R { t.D.D.p.{ E.I.A.`.C C Z Z b b b b b Z R ! ,.,.I.P.1.1X9 9 9 8 9 8 8 8 8 5 8 5 5 5 5 N G.G.#.0XI j 9 5 : : ; ; ; ; : = = * = = = > O.X...Y '.: 2 r N B r 5 : $ # # o + O o O o o o o 1 g g g c +X+X+X+X+X+X+X.X+X+X.X< X X X X X .     ",
"y.A.z.A.,Xl.~ R ~ { i.D.D.p.0.R T Z I.U.h.`.Z C b Z Z Z R ~ 0.q.,.~ G A K.K.#.yXb 9 9 9 8 9 8 8 8 8 5 8 r Z I E K.G.*.).V : : : : : ; : ; ; ; = ; = = = = * M @.@.P 7XD B r , = @ # + + # O + + O O O o o o o % g g g a +X+X+X+X+X+X+X+X+X+X+Xz o o X X X .     ",
"e.D.l.D.,Xj.0.e.D.D.i.0.~ R R b T Z Y.U.j.>XC C C R E ,.q.,.~ Z C b b b -.K.;.rXZ 9 9 9 8 8 8 8 9 C G E Q U Z b o.*.%.n.] : : : : : - ; = ; = = = = = ; 5 7 o.H.H.%.^.F * * @ @ + + + + O + o o O o o o o o o O s g g u ^.+X+X+X+X+X+X+X+X+X+X}.# o X X . .     ",
"a.l.l.z.,XD.D.j.q.~ R R b ~ R ~ T Z s.U.s.,XW ! w.w.0.E Z C C N b b b b &.K.-.>XI 9 9 9 9 N Z R ! Q I C i 8 4 5 P *.%.4.4.4 : : : ; : ; : - ; : 5 7 N V V C x +.@...2.>.@ @ + @ + + + + + + + O O O O o o o o o 1 x _ ^.+X+X+X+X+X+X+X.X+X.X+X.X< X X X X . .   ",
"y.l.k.D.,XD.~ R R R R R T T R T T T s.T.h.rXw.0.E I C N C C N N b b b b #.K.G.).} N C I Q ! Q I C r 5 5 5 5 4 4 n =.*.Q M., : : : : ; ; 2 8 r Z V V B 7 : = : O.X...Y C.@ $ @ + + + + + + O O O O O o O - t ) C.8X+X+X8X+X+X+X+X+X+X+X+X+X+X+X+Xz X X X X . .   ",
"i.l.D.z.,XD.~ R R R R R T T R R ! 0.E.R.h.yXT C C C C C C N N N C b b n W K.G.(.d.{ { E Z B 9 8 8 5 8 5 5 5 5 5 n %.*.L  X4 : : : 8 r C G G Z r 8 : = = = * w O.X...x 0X; @ @ @ @ + + + O + + O $ y / m.+X+X8X+X+X8X+X+X+X+X+X+X+X+X+X+X+X+X+X+X^.O X X . . .   ",
"a.l.l.A.,XD.R R R R R R ~ { e.e.e.,.s.U.s.aXR C C C C C N N N N b b b T $.T.T.A.A.Z N 9 9 8 8 8 8 5 5 5 5 5 5 4 8 %.%.K 9Xh 9 B I G I B 9 5 ; - = = = * = * * p X.X.f XXt * @ + + + + + $ y ^ u.+X8X8X8X+X+X8X+X8X+X+X+X+X+X+X+X+X+X+X+X+X^._ y & O X X X X . . ",
"y.l.A.l.,XD.~ R ~ ! 0.e.j.e.,.~ T Z x.I.r.aXE C C C C C C N N C T ! 0.0.$.I.P.y.S.b 9 8 9 9 8 8 8 8 8 5 5 5 5 5 5 =.=.*.).] I I r 7 : ; ; = = ; - = = = = * = i X.....8.] @ @ + $ 6 H a..X8X8X8X8X+X8X+X8X8X8X+X+X8X8X+X+X+X+X+X+X}.v y - # O O o X X X . . . . ",
"y.l.A.A.,XD.! e.j.j.e.! ~ T b ~ T Z $.U.x.yX{ C C C C C G R { q.q.{ T V P x.G.2.'.9 9 9 9 8 8 8 8 5 8 5 5 5 7 B Z -.K.L.V.<.5 4 : : ; ; ; ; = ; = = = = * * * q X....._ 6., F 7.XX8X8X8X8X8X8X8X8X8X8X8X8X+X8X+X+X+X+X+X+XXX .y < $ # # # # # O o o X X X       ",
"y.A.A.l.,Xj.j.e.{ ~ R R R T R R T Z r.U.x.rX{ C Z R W 0.q.,.~ T C b b b A K.G.,.4X9 9 8 9 9 8 8 8 8 9 N C R E ~ G ;.=.%.<.a.: : : : ; ; ; ; ; = ; = = = = * * : ..d P ` m.0X8X8X8X8X8X0X8X8X8X8X8X+X8X+X8X8X8X+X8XXX) j < - $ $ $ $ $ $ # # O O o               ",
"w.A.A.l.>Xl.~ R R R R R T T T T T T $.I.s.4Xi.{ w.w.0.R T C b N N N b b N K.K.#.yXh 9 9 9 8 9 h C I E E E C h 8 4 A *.&.Q S.: : : ; ; ; ; ; = ; ; = = * = : j ] 8.+XeX8X8X0X8X8X0X8X0X8X8X8X8X8X8X8X8X7X8XXX) l 3 > > : > > = = w * @ @ @                       ",
"y.A.A.A.>X/.~ R R R R T T T T T T T r.E.E.3XA.$.E T C C N N C N b N b b N =.K.#.rXV 9 N C I E ! ! I C 9 7 5 4 5 4 n *.&.P 2X4 : : : : ; ; ; ; ; = : t ) M.7X0XeXeXeX0XeX0X0X0X0X0X0X7X8X8X8X8X8X8XXX[ S 3 : 5 5 4 4 4 : ; ; > = *                               ",
"t.z.A.A.>X/.R ~ R R R R R T R ~ 0.e.e.R.E.;Xh.C C C C C N C b N r N N 9 b -.=.-.].,.E { ! E C N 7 5 8 5 5 5 5 5 4 i %.%.K 9Xr : : : : ; ; ; e _ b.2X0XiX0XeXeX0X0XeX0X8X0X8X0X8X8X8X0X8X8X|.' S e 2 8 b 9 9 5 5 5 4 4 : 4                                       ",
"t.A.A.A.>X/.~ R R R R ~ ,.0.j.e.0.! $.I.U.[.k.C C C C N C b C N N N N N C -.I.U.`.u.I C N 9 8 8 9 8 5 5 5 5 5 4 4 5 *.%.X.F.D : : : 8 / u. X0XiXeXeXeXeXeX0X0XeX0X0X0XeX8XeX0X0X0X|.| D e 6 n N N h i 9 9 0 5 8 5                                               ",
"t.A.A.A.;X:XR ~ ~ 0.e.j.e.0.~ R T T W U.I.:XA.C C C C C b b C b C Z E ! ,.s.I.Y.N.u.9 8 9 8 8 8 8 5 8 5 5 4 5 4 4 4 &.%.%.y.` Y 4.'.eXeXeXeXiX0XeXeXeXeXeX0XeX0X0X0XeX0XeX].3.D e 7 C I Z Z A A N b n 9 9                                                       ",
"t.A.l.A.;XA.e.j.j.e.0.~ T T R T T T ~ I.U.z./.C C C C C C T R { 0.0.! E Z #.G.G.d.M.9 9 9 9 8 8 8 8 5 5 5 5 4 5 5 4 P ;.2.n.0XiXiXeXeXiXiXeX0XiXeXeXeX0X0X0X0XeX0X X3.H h 9 I W R R T Z Z C C N N                                                               ",
"q.S.A.A.;Xz.0.,.~ R R R R T T T n T R I.U././.C C Z R E 0.q.q.~ R C N b 9 L K.G.w.(.9 9 8 8 8 8 8 8 5 5 5 4 8 G 5.B.2XtXtXtXiXeXiXeXeXeXeXeXeXiXeXeXeXeX0X Xt.T B b R $.! ! ~ ~ R R T T Z                                                                       ",
"q.A.A.z.;X:XW R R R R R T T T T T T R I.U.z.-X~ 0.w.q.,.~ Z C N b N N b b P K.G.2.'.9 9 9 8 9 8 8 5 8 V } B.4XiXiXiXiXiXiXiXeXiXeXiXeXiXiXeXeXeXeX X4./ B C ,.e.0.0.,.{ ! ! ~ W                                                                                 ",
"t.A.A.A.>X-XW ~ R R R R T T T T T Z W E.R.(.3Xw.! R C C C N N N b N b b b Z K.G.$.9X9 8 9 8 7 C } b.1XpXpXiXiXpXiXiXiXiXiXiXeXeXiXeXeXeXeX X6.Y C C w.e.e.e.0.0.0.0.,.,.                                                                                        ",
"5.z.A.A.;X-XR R R R R R R T R ~ $.w.e.R.E.h.3XZ C C C C N N N N N N b b n A K.G.#.iXN N ] M.].pXpXpXpXpXpXpXpXiXiXiXiXiXiXiXiXiXiX1Xu.` V G e.z.j.j.f.f.e.e.e.e.                                                                                                ",
"5.A.A.A.-X;X~ R R R R ~ ! 0.j.e.w.,.! U.I.h.qXC C C C C C N N N N b b b b b x.=.$.M.S.tXaXiXpXpXpXpXpXpXpXtXpXtXiXiXtXiXiX1X6.] S G j.  z.z.z.z.z.j.j.j.                                                                                                        ",
"q.A.A.l.;X;XR ~ ! 0.e.j.j.0.~ ~ T Z Z U.U.r.yXZ C C C C N N N N b N N N T a.A.4XpXpXaXaXpXaXpXpXpXpXpXpXpXpXiXpXiXOXu.` V I             z.z.z.                                                                                                                  ",
"5.A.A.A.-X`.e.j.j.e.0.~ R T T T T Z T Y.U.s.jXG C C C N N N N N E t.F.9XsXpXaXaXpXaXpXpXpXpXaXpXpXpXpXpXpX2Xu.[ D R                                                                                                                                             ",
"q.A.A.A.-X:X0.,.~ R R R T T T T Z T Z s.U.r.aXR C C C C T y.S.5XaXaXaXaXsXaXpXaXsXpXpXsXaXpXpXpXpX2Xu.] D I                                                                                                                                                     ",
"<.A.A.A.-X,X~ R R R R R R T T T T Z T x.U.r.jXQ T q.D.1XaXaXaXjXsXaXsXpXaXaXpXaXpXaXaXpXaX1Xd.] G E                                                                                                                                                             ",
"<.(.z.A.-X,XR ~ R R R T T T T T T T T x.s.r.S.`.aXsXdXaXjXjXaXaXaXaXsXaXaXaXaXaXaX4XM.' D E                                                                                                                                                                     ",
"q.A.A.A.-X3XR ~ R R R T T T R Z Z ,.j./.rXsXdXsXdXdXsXsXsXaXsXaXsXaXaXaXaX2Xd.] G E                                                                                                                                                                             ",
"<.A.l.A.-X3X~ R R R R R T { g.`.wXgXfXfXfXsXfXsXdXdXsXsXsXaXaXsXaX4XM.} D                                                                                                                                                                                       ",
"4.D.A.A.:X3XR R R ! i.:XwXfXfXfXfXfXdXdXfXsXsXsXdXfXaXsXaX4XM.} G                                                                                                                                                                                               ",
"q.A.z.l.:XwXp./.5XfXfXfXfXfXfXfXjXdXfXfXsXfXsXsXsX9XM.] D                                                                                                                                                                                                       ",
"<./.-X5XyXgXhXfXgXgXfXfXfXfXfXfXfXdXjXfXjX4Xg.} V                                                                                                                                                                                                               ",
"<.hXgXgXhXhXfXhXgXfXgXfXfXfXfXfXfX4XN.] V                                                                                                                                                                                                                       ",
"<.hXgXgXgXgXfXhXgXfXfXfXfXqXN.] j                                                                                                                                                                                                                               ",
"<.hXgXgXfXhXhXgXfXwXg.} h                                                                                                                                                                                                                                       ",
"<.gXhXgXfXqXN.] t                                                                                                                                                                                                                                               ",
",.rXN.] h                                                                                                                                                                                                                                                       ",
"                                                                                                                                                                                                                                                                ",
"                                                                                                                                                                                                                                                                ",
"                                                                                                                                                                                                                                                                ",
"                                                                                                                                                                                                                                                                ",
"                                                                                                                                                                                                                                                                ",
"                                                                                                                                                                                                                                                                "
};
