enum {
HELP_GLOBAL,
HELP_PATTERN_EDITOR,
HELP_SAMPLE_LIST,
HELP_INSTRUMENT_LIST,
HELP_INFO_PAGE,
HELP_MESSAGE_EDITOR,
HELP_ORDERLIST_PANNING,
HELP_ORDERLIST_VOLUME,
HELP_MIDI_OUTPUT,
HELP_NUM_ITEMS
};
