/*
 * Schism Tracker - a cross-platform Impulse Tracker clone
 * copyright (c) 2003-2005 Storlek <storlek@rigelseven.com>
 * copyright (c) 2005-2008 Mrs. Brisby <mrs.brisby@nimh.org>
 * copyright (c) 2009 Storlek & Mrs. Brisby
 * copyright (c) 2010-2012 Storlek
 * URL: http://schismtracker.org/
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

#ifndef SCHISM_KEYBINDS_H_
#define SCHISM_KEYBINDS_H_

#include "headers.h"

#include "keyboard.h"

/* Okay, this rougly defines the to-be-implemented keybinds crap. */

enum {
	KEYBIND_SECTION_MIDI,
	KEYBIND_SECTION_LOAD_SAMPLE,
	KEYBIND_SECTION_LOAD_STEREO_SAMPLE,
	KEYBIND_SECTION_MESSAGE_EDITOR,
	KEYBIND_SECTION_WATERFALL,
	KEYBIND_SECTION_TIME_INFORMATION,
	KEYBIND_SECTION_LOAD_MODULE,
	KEYBIND_SECTION_PALETTE_EDITOR,
	KEYBIND_SECTION_ORDER_LIST,
	KEYBIND_SECTION_ORDER_LIST_PAN, /* can this just be merged with the above? */
	KEYBIND_SECTION_INFO_PAGE,
	KEYBIND_SECTION_INSTRUMENT_LIST,
	KEYBIND_SECTION_INSTRUMENT_NOTE_TRANSLATION,
	KEYBIND_SECTION_INSTRUMENT_ENVELOPE,
	KEYBIND_SECTION_SAMPLE_LIST,
	KEYBIND_SECTION_PATTERN_EDITOR,
	KEYBIND_SECTION_TRACK_VIEW,
	KEYBIND_SECTION_BLOCK_FUNCTIONS,
	KEYBIND_SECTION_PLAYBACK_FUNCTIONS,
	KEYBIND_SECTION_FILE_LIST,
	KEYBIND_SECTION_GLOBAL,
	KEYBIND_SECTION_DIALOG,
	KEYBIND_SECTION_NOTES,

	/* used for array indices */
	KEYBIND_SECTION_MAX_,
};

enum {
	/* *** MIDI *** */
	KEYBIND_BIND_MIDI_TOGGLE_PORT,

	KEYBIND_BIND_MIDI_MAX_,
};

enum {
	/* *** LOAD SAMPLE *** */
	KEYBIND_BIND_LOAD_SAMPLE_TOGGLE_MULTICHANNEL,

	KEYBIND_BIND_LOAD_SAMPLE_MAX_,
};

enum {
	/* *** LOAD STEREO SAMPLE *** */
	KEYBIND_BIND_LOAD_STEREO_SAMPLE_LOAD_LEFT,
	KEYBIND_BIND_LOAD_STEREO_SAMPLE_LOAD_RIGHT,
	KEYBIND_BIND_LOAD_STEREO_SAMPLE_LOAD_BOTH,

	KEYBIND_BIND_LOAD_STEREO_SAMPLE_MAX_,
};

enum {
	/* *** MESSAGE EDITOR *** */
	KEYBIND_BIND_MESSAGE_EDITOR_EDIT_MESSAGE,
	KEYBIND_BIND_MESSAGE_EDITOR_FINISHED_EDITING,
	KEYBIND_BIND_MESSAGE_EDITOR_TOGGLE_EXTENDED_FONT,
	KEYBIND_BIND_MESSAGE_EDITOR_DELETE_LINE,
	KEYBIND_BIND_MESSAGE_EDITOR_CLEAR_MESSAGE,
	KEYBIND_BIND_MESSAGE_EDITOR_GOTO_FIRST_LINE,
	KEYBIND_BIND_MESSAGE_EDITOR_GOTO_LAST_LINE,

	KEYBIND_BIND_MESSAGE_EDITOR_MAX_,
};

enum {
	/* *** WATERFALL *** */
	KEYBIND_BIND_WATERFALL_SONG_TOGGLE_STEREO,
	KEYBIND_BIND_WATERFALL_SONG_FLIP_STEREO,
	KEYBIND_BIND_WATERFALL_VIEW_TOGGLE_MONO,
	KEYBIND_BIND_WATERFALL_DECREASE_SENSITIVITY,
	KEYBIND_BIND_WATERFALL_INCREASE_SENSITIVITY,
	KEYBIND_BIND_WATERFALL_GOTO_NEXT_ORDER,
	KEYBIND_BIND_WATERFALL_GOTO_PREVIOUS_ORDER,
	KEYBIND_BIND_WATERFALL_GOTO_NEXT_CHANNEL,
	KEYBIND_BIND_WATERFALL_GOTO_PREVIOUS_CHANNEL,
	KEYBIND_BIND_WATERFALL_GOTO_NEXT_INSTRUMENT,
	KEYBIND_BIND_WATERFALL_GOTO_PREVIOUS_INSTRUMENT,
	KEYBIND_BIND_WATERFALL_GOTO_PATTERN_EDIT,

	KEYBIND_BIND_WATERFALL_MAX_,
};

enum {
	/* *** TIME INFORMATION *** */
	KEYBIND_BIND_TIME_INFORMATION_TOGGLE_SESSION,

	KEYBIND_BIND_TIME_INFORMATION_MAX_,
};

enum {
	/* *** LOAD MODULE *** */
	KEYBIND_BIND_LOAD_MODULE_SHOW_SONG_LENGTH,
	KEYBIND_BIND_LOAD_MODULE_CLEAR_SEARCH_TEXT,

	KEYBIND_BIND_LOAD_MODULE_MAX_,
};

enum {
	/* *** PALETTE EDITOR *** */
	KEYBIND_BIND_PALETTE_EDITOR_COPY,
	KEYBIND_BIND_PALETTE_EDITOR_PASTE,

	KEYBIND_BIND_PALETTE_EDITOR_MAX_,
};

enum {
	/* *** ORDER LIST *** */
	KEYBIND_BIND_ORDER_LIST_GOTO_SELECTED_PATTERN,
	KEYBIND_BIND_ORDER_LIST_SELECT_ORDER_FOR_PLAYBACK,
	KEYBIND_BIND_ORDER_LIST_PLAY_FROM_ORDER,
	KEYBIND_BIND_ORDER_LIST_INSERT_NEXT_PATTERN,
	KEYBIND_BIND_ORDER_LIST_DUPLICATE_PATTERN,
	KEYBIND_BIND_ORDER_LIST_MARK_END_OF_SONG,
	KEYBIND_BIND_ORDER_LIST_SKIP_TO_NEXT_ORDER_MARK,
	KEYBIND_BIND_ORDER_LIST_INSERT_PATTERN,
	KEYBIND_BIND_ORDER_LIST_DELETE_PATTERN,
	KEYBIND_BIND_ORDER_LIST_SORT_ORDER_LIST,
	KEYBIND_BIND_ORDER_LIST_FIND_UNUSED_PATTERNS,
	KEYBIND_BIND_ORDER_LIST_LINK_PATTERN_TO_SAMPLE,
	KEYBIND_BIND_ORDER_LIST_COPY_PATTERN_TO_SAMPLE,
	KEYBIND_BIND_ORDER_LIST_COPY_PATTERN_TO_SAMPLE_WITH_SPLIT,
	KEYBIND_BIND_ORDER_LIST_CONTINUE_NEXT_POSITION_OF_PATTERN,
	KEYBIND_BIND_ORDER_LIST_SAVE_ORDER_LIST,
	KEYBIND_BIND_ORDER_LIST_RESTORE_ORDER_LIST,
	KEYBIND_BIND_ORDER_LIST_DECREASE_INSTRUMENT,
	KEYBIND_BIND_ORDER_LIST_INCREASE_INSTRUMENT,

	KEYBIND_BIND_ORDER_LIST_MAX_,
};

enum {
	/* *** ORDER LIST PAN *** */
	KEYBIND_BIND_ORDER_LIST_PAN_TOGGLE_CHANNEL_MUTE,
	KEYBIND_BIND_ORDER_LIST_PAN_SET_PANNING_LEFT,
	KEYBIND_BIND_ORDER_LIST_PAN_SET_PANNING_MIDDLE,
	KEYBIND_BIND_ORDER_LIST_PAN_SET_PANNING_RIGHT,
	KEYBIND_BIND_ORDER_LIST_PAN_SET_PANNING_SURROUND,
	KEYBIND_BIND_ORDER_LIST_PAN_PAN_UNMUTED_LEFT,
	KEYBIND_BIND_ORDER_LIST_PAN_PAN_UNMUTED_MIDDLE,
	KEYBIND_BIND_ORDER_LIST_PAN_PAN_UNMUTED_RIGHT,
	KEYBIND_BIND_ORDER_LIST_PAN_PAN_UNMUTED_STEREO,
	KEYBIND_BIND_ORDER_LIST_PAN_PAN_UNMUTED_AMIGA_STEREO,
	KEYBIND_BIND_ORDER_LIST_PAN_LINEAR_PANNING_LEFT_TO_RIGHT,
	KEYBIND_BIND_ORDER_LIST_PAN_LINEAR_PANNING_RIGHT_TO_LEFT,

	KEYBIND_BIND_ORDER_LIST_PAN_MAX_,
};

enum {
	/* *** INFO PAGE *** */
	KEYBIND_BIND_INFO_PAGE_ADD_WINDOW,
	KEYBIND_BIND_INFO_PAGE_DELETE_WINDOW,
	KEYBIND_BIND_INFO_PAGE_NAV_NEXT_WINDOW,
	KEYBIND_BIND_INFO_PAGE_NAV_PREVIOUS_WINDOW,
	KEYBIND_BIND_INFO_PAGE_CHANGE_WINDOW_TYPE_UP,
	KEYBIND_BIND_INFO_PAGE_CHANGE_WINDOW_TYPE_DOWN,
	KEYBIND_BIND_INFO_PAGE_MOVE_WINDOW_BASE_UP,
	KEYBIND_BIND_INFO_PAGE_MOVE_WINDOW_BASE_DOWN,
	KEYBIND_BIND_INFO_PAGE_TOGGLE_VOLUME_VELOCITY_BARS,
	KEYBIND_BIND_INFO_PAGE_TOGGLE_SAMPLE_INSTRUMENT_NAMES,
	KEYBIND_BIND_INFO_PAGE_TOGGLE_CHANNEL_MUTE,
	KEYBIND_BIND_INFO_PAGE_TOGGLE_CHANNEL_MUTE_AND_GO_NEXT,
	KEYBIND_BIND_INFO_PAGE_SOLO_CHANNEL,
	KEYBIND_BIND_INFO_PAGE_GOTO_NEXT_PATTERN,
	KEYBIND_BIND_INFO_PAGE_GOTO_PREVIOUS_PATTERN,
	KEYBIND_BIND_INFO_PAGE_TOGGLE_STEREO_PLAYBACK,
	KEYBIND_BIND_INFO_PAGE_REVERSE_OUTPUT_CHANNELS,
	KEYBIND_BIND_INFO_PAGE_GOTO_PLAYING_PATTERN,

	KEYBIND_BIND_INFO_PAGE_MAX_,
};

enum {
	/* *** INSTRUMENT LIST *** */
	KEYBIND_BIND_INSTRUMENT_LIST_NEXT_PAGE,
	KEYBIND_BIND_INSTRUMENT_LIST_PREVIOUS_PAGE,
	KEYBIND_BIND_INSTRUMENT_LIST_MOVE_INSTRUMENT_UP,
	KEYBIND_BIND_INSTRUMENT_LIST_MOVE_INSTRUMENT_DOWN,
	KEYBIND_BIND_INSTRUMENT_LIST_GOTO_FIRST_INSTRUMENT,
	KEYBIND_BIND_INSTRUMENT_LIST_GOTO_LAST_INSTRUMENT,
	KEYBIND_BIND_INSTRUMENT_LIST_FOCUS_LIST,
	KEYBIND_BIND_INSTRUMENT_LIST_GOTO_INSTRUMENT_UP,
	KEYBIND_BIND_INSTRUMENT_LIST_GOTO_INSTRUMENT_DOWN,
	KEYBIND_BIND_INSTRUMENT_LIST_CLEAR_NAME_AND_FILENAME,
	KEYBIND_BIND_INSTRUMENT_LIST_WIPE_DATA,
	KEYBIND_BIND_INSTRUMENT_LIST_EDIT_NAME,
	KEYBIND_BIND_INSTRUMENT_LIST_DELETE_INSTRUMENT_AND_SAMPLES,
	KEYBIND_BIND_INSTRUMENT_LIST_DELETE_INSTRUMENT_AND_UNUSED_SAMPLES,
	KEYBIND_BIND_INSTRUMENT_LIST_POST_LOOP_CUT,
	KEYBIND_BIND_INSTRUMENT_LIST_TOGGLE_MULTICHANNEL,
	KEYBIND_BIND_INSTRUMENT_LIST_SAVE_TO_DISK,
	KEYBIND_BIND_INSTRUMENT_LIST_SAVE_TO_DISK_EXP,
	KEYBIND_BIND_INSTRUMENT_LIST_COPY,
	KEYBIND_BIND_INSTRUMENT_LIST_REPLACE_IN_SONG,
	KEYBIND_BIND_INSTRUMENT_LIST_SWAP,
	KEYBIND_BIND_INSTRUMENT_LIST_EXCHANGE,
	KEYBIND_BIND_INSTRUMENT_LIST_INSERT_SLOT,
	KEYBIND_BIND_INSTRUMENT_LIST_REMOVE_SLOT,
	KEYBIND_BIND_INSTRUMENT_LIST_INCREASE_PLAYBACK_CHANNEL,
	KEYBIND_BIND_INSTRUMENT_LIST_DECREASE_PLAYBACK_CHANNEL,

	KEYBIND_BIND_INSTRUMENT_LIST_MAX_,
};

enum {
	/* *** INSTRUMENT NOTE TRANSLATION *** */
	KEYBIND_BIND_INSTRUMENT_NOTE_TRANSLATION_PICKUP_SAMPLE_NUMBER_AND_DEFAULT_PLAY_NOTE,
	KEYBIND_BIND_INSTRUMENT_NOTE_TRANSLATION_INCREASE_SAMPLE_NUMBER,
	KEYBIND_BIND_INSTRUMENT_NOTE_TRANSLATION_DECREASE_SAMPLE_NUMBER,
	KEYBIND_BIND_INSTRUMENT_NOTE_TRANSLATION_CHANGE_ALL_SAMPLES,
	KEYBIND_BIND_INSTRUMENT_NOTE_TRANSLATION_CHANGE_ALL_SAMPLES_WITH_NAME,
	KEYBIND_BIND_INSTRUMENT_NOTE_TRANSLATION_ENTER_NEXT_NOTE,
	KEYBIND_BIND_INSTRUMENT_NOTE_TRANSLATION_ENTER_PREVIOUS_NOTE,
	KEYBIND_BIND_INSTRUMENT_NOTE_TRANSLATION_TRANSPOSE_ALL_NOTES_SEMITONE_UP,
	KEYBIND_BIND_INSTRUMENT_NOTE_TRANSLATION_TRANSPOSE_ALL_NOTES_SEMITONE_DOWN,
	KEYBIND_BIND_INSTRUMENT_NOTE_TRANSLATION_INSERT_ROW_FROM_TABLE,
	KEYBIND_BIND_INSTRUMENT_NOTE_TRANSLATION_DELETE_ROW_FROM_TABLE,
	KEYBIND_BIND_INSTRUMENT_NOTE_TRANSLATION_TOGGLE_EDIT_MASK,

	KEYBIND_BIND_INSTRUMENT_NOTE_TRANSLATION_MAX_,
};

enum {
	/* *** INSTRUMENT ENVELOPE *** */
	KEYBIND_BIND_INSTRUMENT_ENVELOPE_PICKUP_SAMPLE_NUMBER_AND_DEFAULT_PLAY_NOTE,
	KEYBIND_BIND_INSTRUMENT_ENVELOPE_INCREASE_SAMPLE_NUMBER,
	KEYBIND_BIND_INSTRUMENT_ENVELOPE_DECREASE_SAMPLE_NUMBER,
	KEYBIND_BIND_INSTRUMENT_ENVELOPE_CHANGE_ALL_SAMPLES,
	KEYBIND_BIND_INSTRUMENT_ENVELOPE_CHANGE_ALL_SAMPLES_WITH_NAME,
	KEYBIND_BIND_INSTRUMENT_ENVELOPE_ENTER_NEXT_NOTE,
	KEYBIND_BIND_INSTRUMENT_ENVELOPE_ENTER_PREVIOUS_NOTE,
	KEYBIND_BIND_INSTRUMENT_ENVELOPE_TRANSPOSE_ALL_NOTES_SEMITONE_UP,
	KEYBIND_BIND_INSTRUMENT_ENVELOPE_TRANSPOSE_ALL_NOTES_SEMITONE_DOWN,
	KEYBIND_BIND_INSTRUMENT_ENVELOPE_INSERT_ROW_FROM_TABLE,
	KEYBIND_BIND_INSTRUMENT_ENVELOPE_DELETE_ROW_FROM_TABLE,
	KEYBIND_BIND_INSTRUMENT_ENVELOPE_TOGGLE_EDIT_MASK,

	KEYBIND_BIND_INSTRUMENT_ENVELOPE_MAX_,
};

enum {
	/* *** SAMPLE LIST *** */
	KEYBIND_BIND_SAMPLE_LIST_MOVE_UP,
	KEYBIND_BIND_SAMPLE_LIST_MOVE_DOWN,
	KEYBIND_BIND_SAMPLE_LIST_FOCUS_SAMPLE_LIST,
	KEYBIND_BIND_SAMPLE_LIST_GOTO_FIRST_SAMPLE,
	KEYBIND_BIND_SAMPLE_LIST_GOTO_LAST_SAMPLE,
	KEYBIND_BIND_SAMPLE_LIST_CONVERT_SIGNED_UNSIGNED,
	KEYBIND_BIND_SAMPLE_LIST_PRE_LOOP_CUT,
	KEYBIND_BIND_SAMPLE_LIST_CLEAR_NAME_AND_FILENAME,
	KEYBIND_BIND_SAMPLE_LIST_DELETE_SAMPLE,
	KEYBIND_BIND_SAMPLE_LIST_DOWNMIX_TO_MONO,
	KEYBIND_BIND_SAMPLE_LIST_RESIZE_SAMPLE_WITH_INTERPOLATION,
	KEYBIND_BIND_SAMPLE_LIST_RESIZE_SAMPLE_WITHOUT_INTERPOLATION,
	KEYBIND_BIND_SAMPLE_LIST_REVERSE_SAMPLE,
	KEYBIND_BIND_SAMPLE_LIST_CENTRALISE_SAMPLE,
	KEYBIND_BIND_SAMPLE_LIST_INVERT_SAMPLE,
	KEYBIND_BIND_SAMPLE_LIST_POST_LOOP_CUT,
	KEYBIND_BIND_SAMPLE_LIST_SAMPLE_AMPLIFIER,
	KEYBIND_BIND_SAMPLE_LIST_TOGGLE_MULTICHANNEL_PLAYBACK,
	KEYBIND_BIND_SAMPLE_LIST_SAVE_SAMPLE_TO_DISK_IT,
	KEYBIND_BIND_SAMPLE_LIST_COPY_SAMPLE,
	KEYBIND_BIND_SAMPLE_LIST_TOGGLE_SAMPLE_QUALITY,
	KEYBIND_BIND_SAMPLE_LIST_REPLACE_CURRENT_SAMPLE,
	KEYBIND_BIND_SAMPLE_LIST_SWAP_SAMPLE,
	KEYBIND_BIND_SAMPLE_LIST_SAVE_SAMPLE_TO_DISK_FORMAT_SELECT,
	KEYBIND_BIND_SAMPLE_LIST_SAVE_SAMPLE_TO_DISK_RAW,
	KEYBIND_BIND_SAMPLE_LIST_EXCHANGE_SAMPLE,
	KEYBIND_BIND_SAMPLE_LIST_TEXT_TO_SAMPLE,
	KEYBIND_BIND_SAMPLE_LIST_EDIT_CREATE_ADLIB_SAMPLE,
	KEYBIND_BIND_SAMPLE_LIST_LOAD_ADLIB_SAMPLE_BY_MIDI_PATCH_NUMBER,
	KEYBIND_BIND_SAMPLE_LIST_INSERT_SAMPLE_SLOT,
	KEYBIND_BIND_SAMPLE_LIST_REMOVE_SAMPLE_SLOT,
	KEYBIND_BIND_SAMPLE_LIST_SWAP_SAMPLE_WITH_PREVIOUS,
	KEYBIND_BIND_SAMPLE_LIST_SWAP_SAMPLE_WITH_NEXT,
	KEYBIND_BIND_SAMPLE_LIST_TOGGLE_CURRENT_SAMPLE,
	KEYBIND_BIND_SAMPLE_LIST_SOLO_CURRENT_SAMPLE,
	KEYBIND_BIND_SAMPLE_LIST_DECREASE_PLAYBACK_CHANNEL,
	KEYBIND_BIND_SAMPLE_LIST_INCREASE_PLAYBACK_CHANNEL,
	KEYBIND_BIND_SAMPLE_LIST_INCREASE_C5_FREQUENCY_1_OCTAVE,
	KEYBIND_BIND_SAMPLE_LIST_DECREASE_C5_FREQUENCY_1_OCTAVE,
	KEYBIND_BIND_SAMPLE_LIST_INCREASE_C5_FREQUENCY_1_SEMITONE,
	KEYBIND_BIND_SAMPLE_LIST_DECREASE_C5_FREQUENCY_1_SEMITONE,
	KEYBIND_BIND_SAMPLE_LIST_INSERT_ARROW_UP,

	KEYBIND_BIND_SAMPLE_LIST_MAX_,
};

enum {
	/* *** PATTERN EDITOR *** */
	KEYBIND_BIND_PATTERN_EDITOR_NEXT_PATTERN,
	KEYBIND_BIND_PATTERN_EDITOR_PREVIOUS_PATTERN,
	KEYBIND_BIND_PATTERN_EDITOR_NEXT_4_PATTERN,
	KEYBIND_BIND_PATTERN_EDITOR_PREVIOUS_4_PATTERN,
	KEYBIND_BIND_PATTERN_EDITOR_NEXT_ORDER_PATTERN,
	KEYBIND_BIND_PATTERN_EDITOR_PREVIOUS_ORDER_PATTERN,
	KEYBIND_BIND_PATTERN_EDITOR_CLEAR_FIELD,
	KEYBIND_BIND_PATTERN_EDITOR_NOTE_CUT,
	KEYBIND_BIND_PATTERN_EDITOR_NOTE_OFF,
	KEYBIND_BIND_PATTERN_EDITOR_TOGGLE_VOLUME_PANNING,
	KEYBIND_BIND_PATTERN_EDITOR_NOTE_FADE,
	KEYBIND_BIND_PATTERN_EDITOR_USE_LAST_VALUE,
	KEYBIND_BIND_PATTERN_EDITOR_GET_DEFAULT_VALUE,
	KEYBIND_BIND_PATTERN_EDITOR_DECREASE_INSTRUMENT,
	KEYBIND_BIND_PATTERN_EDITOR_INCREASE_INSTRUMENT,
	KEYBIND_BIND_PATTERN_EDITOR_TOGGLE_EDIT_MASK,
	KEYBIND_BIND_PATTERN_EDITOR_INSERT_ROW,
	KEYBIND_BIND_PATTERN_EDITOR_DELETE_ROW,
	KEYBIND_BIND_PATTERN_EDITOR_INSERT_PATTERN_ROW,
	KEYBIND_BIND_PATTERN_EDITOR_DELETE_PATTERN_ROW,
	KEYBIND_BIND_PATTERN_EDITOR_UP_BY_SKIP,
	KEYBIND_BIND_PATTERN_EDITOR_DOWN_BY_SKIP,
	KEYBIND_BIND_PATTERN_EDITOR_SET_SKIP_1,
	KEYBIND_BIND_PATTERN_EDITOR_SET_SKIP_2,
	KEYBIND_BIND_PATTERN_EDITOR_SET_SKIP_3,
	KEYBIND_BIND_PATTERN_EDITOR_SET_SKIP_4,
	KEYBIND_BIND_PATTERN_EDITOR_SET_SKIP_5,
	KEYBIND_BIND_PATTERN_EDITOR_SET_SKIP_6,
	KEYBIND_BIND_PATTERN_EDITOR_SET_SKIP_7,
	KEYBIND_BIND_PATTERN_EDITOR_SET_SKIP_8,
	KEYBIND_BIND_PATTERN_EDITOR_SET_SKIP_9,
	KEYBIND_BIND_PATTERN_EDITOR_UP_ONE_ROW,
	KEYBIND_BIND_PATTERN_EDITOR_DOWN_ONE_ROW,
	KEYBIND_BIND_PATTERN_EDITOR_SLIDE_PATTERN_UP,
	KEYBIND_BIND_PATTERN_EDITOR_SLIDE_PATTERN_DOWN,
	KEYBIND_BIND_PATTERN_EDITOR_MOVE_CURSOR_LEFT,
	KEYBIND_BIND_PATTERN_EDITOR_MOVE_CURSOR_RIGHT,
	KEYBIND_BIND_PATTERN_EDITOR_MOVE_FORWARDS_CHANNEL,
	KEYBIND_BIND_PATTERN_EDITOR_MOVE_BACKWARDS_CHANNEL,
	KEYBIND_BIND_PATTERN_EDITOR_MOVE_FORWARDS_NOTE_COLUMN,
	KEYBIND_BIND_PATTERN_EDITOR_MOVE_BACKWARDS_NOTE_COLUMN,
	KEYBIND_BIND_PATTERN_EDITOR_MOVE_UP_N_LINES,
	KEYBIND_BIND_PATTERN_EDITOR_MOVE_DOWN_N_LINES,
	KEYBIND_BIND_PATTERN_EDITOR_MOVE_PATTERN_TOP,
	KEYBIND_BIND_PATTERN_EDITOR_MOVE_PATTERN_BOTTOM,
	KEYBIND_BIND_PATTERN_EDITOR_MOVE_START,
	KEYBIND_BIND_PATTERN_EDITOR_MOVE_END,
	KEYBIND_BIND_PATTERN_EDITOR_MOVE_PREVIOUS_POSITION,
	KEYBIND_BIND_PATTERN_EDITOR_MOVE_PREVIOUS,
	KEYBIND_BIND_PATTERN_EDITOR_MOVE_NEXT,
	KEYBIND_BIND_PATTERN_EDITOR_TOGGLE_MULTICHANNEL,
	KEYBIND_BIND_PATTERN_EDITOR_STORE_PATTERN_DATA,
	KEYBIND_BIND_PATTERN_EDITOR_REVERT_PATTERN_DATA,
	KEYBIND_BIND_PATTERN_EDITOR_UNDO,
	KEYBIND_BIND_PATTERN_EDITOR_TOGGLE_CENTRALISE_CURSOR,
	KEYBIND_BIND_PATTERN_EDITOR_TOGGLE_HIGHLIGHT_ROW,
	KEYBIND_BIND_PATTERN_EDITOR_TOGGLE_VOLUME_DISPLAY,
	KEYBIND_BIND_PATTERN_EDITOR_SET_PATTERN_LENGTH,
	KEYBIND_BIND_PATTERN_EDITOR_TOGGLE_MIDI_TRIGGER,

	KEYBIND_BIND_PATTERN_EDITOR_MAX_,
};

enum {
	/* *** TRACK VIEW *** */
	KEYBIND_BIND_TRACK_VIEW_CYCLE_VIEW,
	KEYBIND_BIND_TRACK_VIEW_CLEAR_TRACK_VIEWS,
	KEYBIND_BIND_TRACK_VIEW_TOGGLE_TRACK_VIEW_DIVISIONS,
	KEYBIND_BIND_TRACK_VIEW_TRACK_SCHEME_DEFAULT,
	KEYBIND_BIND_TRACK_VIEW_TRACK_SCHEME_1,
	KEYBIND_BIND_TRACK_VIEW_TRACK_SCHEME_2,
	KEYBIND_BIND_TRACK_VIEW_TRACK_SCHEME_3,
	KEYBIND_BIND_TRACK_VIEW_TRACK_SCHEME_4,
	KEYBIND_BIND_TRACK_VIEW_TRACK_SCHEME_5,
	KEYBIND_BIND_TRACK_VIEW_TRACK_SCHEME_6,
	KEYBIND_BIND_TRACK_VIEW_QUICK_VIEW_SCHEME_DEFAULT,
	KEYBIND_BIND_TRACK_VIEW_QUICK_VIEW_SCHEME_1,
	KEYBIND_BIND_TRACK_VIEW_QUICK_VIEW_SCHEME_2,
	KEYBIND_BIND_TRACK_VIEW_QUICK_VIEW_SCHEME_3,
	KEYBIND_BIND_TRACK_VIEW_QUICK_VIEW_SCHEME_4,
	KEYBIND_BIND_TRACK_VIEW_QUICK_VIEW_SCHEME_5,
	KEYBIND_BIND_TRACK_VIEW_QUICK_VIEW_SCHEME_6,

	KEYBIND_BIND_TRACK_VIEW_MAX_,
};

enum {
	/* *** BLOCK FUNCTIONS *** */
	KEYBIND_BIND_BLOCK_FUNCTIONS_MARK_BEGINNING_BLOCK,
	KEYBIND_BIND_BLOCK_FUNCTIONS_MARK_END_BLOCK,
	KEYBIND_BIND_BLOCK_FUNCTIONS_QUICK_MARK_LINES,
	KEYBIND_BIND_BLOCK_FUNCTIONS_MARK_COLUMN_OR_PATTERN,
	KEYBIND_BIND_BLOCK_FUNCTIONS_MARK_BLOCK_LEFT,
	KEYBIND_BIND_BLOCK_FUNCTIONS_MARK_BLOCK_RIGHT,
	KEYBIND_BIND_BLOCK_FUNCTIONS_MARK_BLOCK_UP,
	KEYBIND_BIND_BLOCK_FUNCTIONS_MARK_BLOCK_DOWN,
	KEYBIND_BIND_BLOCK_FUNCTIONS_MARK_BLOCK_START_ROW,
	KEYBIND_BIND_BLOCK_FUNCTIONS_MARK_BLOCK_END_ROW,
	KEYBIND_BIND_BLOCK_FUNCTIONS_MARK_BLOCK_PAGE_UP,
	KEYBIND_BIND_BLOCK_FUNCTIONS_MARK_BLOCK_PAGE_DOWN,
	KEYBIND_BIND_BLOCK_FUNCTIONS_UNMARK,
	KEYBIND_BIND_BLOCK_FUNCTIONS_RAISE_NOTES_SEMITONE,
	KEYBIND_BIND_BLOCK_FUNCTIONS_RAISE_NOTES_OCTAVE,
	KEYBIND_BIND_BLOCK_FUNCTIONS_LOWER_NOTES_SEMITONE,
	KEYBIND_BIND_BLOCK_FUNCTIONS_LOWER_NOTES_OCTAVE,
	KEYBIND_BIND_BLOCK_FUNCTIONS_SET_INSTRUMENT,
	KEYBIND_BIND_BLOCK_FUNCTIONS_SET_VOLUME_OR_PANNING,
	KEYBIND_BIND_BLOCK_FUNCTIONS_WIPE_VOLUME_OR_PANNING,
	KEYBIND_BIND_BLOCK_FUNCTIONS_SLIDE_VOLUME_OR_PANNING,
	KEYBIND_BIND_BLOCK_FUNCTIONS_VOLUME_AMPLIFIER,
	KEYBIND_BIND_BLOCK_FUNCTIONS_CUT_BLOCK,
	KEYBIND_BIND_BLOCK_FUNCTIONS_SWAP_BLOCK,
	KEYBIND_BIND_BLOCK_FUNCTIONS_SLIDE_EFFECT_VALUE,
	KEYBIND_BIND_BLOCK_FUNCTIONS_ROLL_BLOCK_DOWN,
	KEYBIND_BIND_BLOCK_FUNCTIONS_ROLL_BLOCK_UP,
	KEYBIND_BIND_BLOCK_FUNCTIONS_COPY_BLOCK,
	KEYBIND_BIND_BLOCK_FUNCTIONS_COPY_BLOCK_WITH_MUTE,
	KEYBIND_BIND_BLOCK_FUNCTIONS_PASTE_DATA,
	KEYBIND_BIND_BLOCK_FUNCTIONS_PASTE_AND_OVERWRITE,
	KEYBIND_BIND_BLOCK_FUNCTIONS_PASTE_AND_MIX,
	KEYBIND_BIND_BLOCK_FUNCTIONS_DOUBLE_BLOCK_LENGTH,
	KEYBIND_BIND_BLOCK_FUNCTIONS_HALVE_BLOCK_LENGTH,
	KEYBIND_BIND_BLOCK_FUNCTIONS_SELECT_TEMPLATE_MODE,
	KEYBIND_BIND_BLOCK_FUNCTIONS_DISABLE_TEMPLATE_MODE,
	KEYBIND_BIND_BLOCK_FUNCTIONS_TOGGLE_FAST_VOLUME,
	KEYBIND_BIND_BLOCK_FUNCTIONS_SELECTION_VOLUME_VARY,
	KEYBIND_BIND_BLOCK_FUNCTIONS_SELECTION_PANNING_VARY,
	KEYBIND_BIND_BLOCK_FUNCTIONS_SELECTION_EFFECT_VARY,

	KEYBIND_BIND_BLOCK_FUNCTIONS_MAX_,
};

enum {
	/* *** PLAYBACK FUNCTIONS *** */
	KEYBIND_BIND_PLAYBACK_FUNCTIONS_PLAY_NOTE_CURSOR,
	KEYBIND_BIND_PLAYBACK_FUNCTIONS_PLAY_ROW,
	KEYBIND_BIND_PLAYBACK_FUNCTIONS_PLAY_FROM_ROW,
	KEYBIND_BIND_PLAYBACK_FUNCTIONS_TOGGLE_PLAYBACK_MARK,
	KEYBIND_BIND_PLAYBACK_FUNCTIONS_TOGGLE_CURRENT_CHANNEL,
	KEYBIND_BIND_PLAYBACK_FUNCTIONS_SOLO_CURRENT_CHANNEL,

	KEYBIND_BIND_PLAYBACK_FUNCTIONS_MAX_,
};

enum {
	/* *** FILE LIST *** */
	KEYBIND_BIND_FILE_LIST_DELETE,

	KEYBIND_BIND_FILE_LIST_MAX_,
};

enum {
	/* *** GLOBAL *** */
	KEYBIND_BIND_GLOBAL_HELP,
	KEYBIND_BIND_GLOBAL_MIDI,
	KEYBIND_BIND_GLOBAL_SYSTEM_CONFIGURE,
	KEYBIND_BIND_GLOBAL_PATTERN_EDIT,
	KEYBIND_BIND_GLOBAL_SAMPLE_LIST,
	KEYBIND_BIND_GLOBAL_SAMPLE_LIBRARY,
	KEYBIND_BIND_GLOBAL_INSTRUMENT_LIST,
	KEYBIND_BIND_GLOBAL_INSTRUMENT_LIBRARY,
	KEYBIND_BIND_GLOBAL_PLAY_INFORMATION_OR_PLAY_SONG,
	KEYBIND_BIND_GLOBAL_PLAY_SONG,
	KEYBIND_BIND_GLOBAL_PREFERENCES,
	KEYBIND_BIND_GLOBAL_PLAY_CURRENT_PATTERN,
	KEYBIND_BIND_GLOBAL_PLAY_SONG_FROM_ORDER,
	KEYBIND_BIND_GLOBAL_PLAY_SONG_FROM_MARK,
	KEYBIND_BIND_GLOBAL_TOGGLE_PLAYBACK,
	KEYBIND_BIND_GLOBAL_STOP_PLAYBACK,
	KEYBIND_BIND_GLOBAL_TOGGLE_PLAYBACK_TRACING,
	KEYBIND_BIND_GLOBAL_TOGGLE_MIDI_INPUT,
	KEYBIND_BIND_GLOBAL_LOAD_MODULE,
	KEYBIND_BIND_GLOBAL_MESSAGE_EDITOR,
	KEYBIND_BIND_GLOBAL_SAVE_MODULE,
	KEYBIND_BIND_GLOBAL_EXPORT_MODULE,
	KEYBIND_BIND_GLOBAL_ORDER_LIST_PANNING,
	KEYBIND_BIND_GLOBAL_ORDER_LIST_VOLUME,
	KEYBIND_BIND_GLOBAL_ORDER_LIST_LOCK,
	KEYBIND_BIND_GLOBAL_SCHISM_LOGGING,
	KEYBIND_BIND_GLOBAL_SONG_VARIABLES,
	KEYBIND_BIND_GLOBAL_PALETTE_CONFIG,
	KEYBIND_BIND_GLOBAL_FONT_EDITOR,
	KEYBIND_BIND_GLOBAL_WATERFALL,
	KEYBIND_BIND_GLOBAL_TIME_INFORMATION,
	KEYBIND_BIND_GLOBAL_OCTAVE_DECREASE,
	KEYBIND_BIND_GLOBAL_OCTAVE_INCREASE,
	KEYBIND_BIND_GLOBAL_DECREASE_PLAYBACK_SPEED,
	KEYBIND_BIND_GLOBAL_INCREASE_PLAYBACK_SPEED,
	KEYBIND_BIND_GLOBAL_DECREASE_PLAYBACK_TEMPO,
	KEYBIND_BIND_GLOBAL_INCREASE_PLAYBACK_TEMPO,
	KEYBIND_BIND_GLOBAL_DECREASE_GLOBAL_VOLUME,
	KEYBIND_BIND_GLOBAL_INCREASE_GLOBAL_VOLUME,
	KEYBIND_BIND_GLOBAL_TOGGLE_CHANNEL_1,
	KEYBIND_BIND_GLOBAL_TOGGLE_CHANNEL_2,
	KEYBIND_BIND_GLOBAL_TOGGLE_CHANNEL_3,
	KEYBIND_BIND_GLOBAL_TOGGLE_CHANNEL_4,
	KEYBIND_BIND_GLOBAL_TOGGLE_CHANNEL_5,
	KEYBIND_BIND_GLOBAL_TOGGLE_CHANNEL_6,
	KEYBIND_BIND_GLOBAL_TOGGLE_CHANNEL_7,
	KEYBIND_BIND_GLOBAL_TOGGLE_CHANNEL_8,
	KEYBIND_BIND_GLOBAL_MOUSE_GRAB,
	KEYBIND_BIND_GLOBAL_DISPLAY_RESET,
	KEYBIND_BIND_GLOBAL_GO_TO_TIME,
	KEYBIND_BIND_GLOBAL_AUDIO_RESET,
	KEYBIND_BIND_GLOBAL_MOUSE,
	KEYBIND_BIND_GLOBAL_NEW_SONG,
	KEYBIND_BIND_GLOBAL_CALCULATE_SONG_LENGTH,
	KEYBIND_BIND_GLOBAL_QUIT,
	KEYBIND_BIND_GLOBAL_QUIT_NO_CONFIRM,
	KEYBIND_BIND_GLOBAL_SAVE,
	KEYBIND_BIND_GLOBAL_PREVIOUS_ORDER,
	KEYBIND_BIND_GLOBAL_NEXT_ORDER,
	KEYBIND_BIND_GLOBAL_FULLSCREEN,
	KEYBIND_BIND_GLOBAL_OPEN_MENU,
	KEYBIND_BIND_GLOBAL_NAV_LEFT,
	KEYBIND_BIND_GLOBAL_NAV_RIGHT,
	KEYBIND_BIND_GLOBAL_NAV_UP,
	KEYBIND_BIND_GLOBAL_NAV_DOWN,
	KEYBIND_BIND_GLOBAL_NAV_PAGE_UP,
	KEYBIND_BIND_GLOBAL_NAV_PAGE_DOWN,
	KEYBIND_BIND_GLOBAL_NAV_ACCEPT,
	KEYBIND_BIND_GLOBAL_NAV_CANCEL,
	KEYBIND_BIND_GLOBAL_NAV_HOME,
	KEYBIND_BIND_GLOBAL_NAV_END,
	KEYBIND_BIND_GLOBAL_NAV_TAB,
	KEYBIND_BIND_GLOBAL_NAV_BACKTAB,
	KEYBIND_BIND_GLOBAL_NUMENTRY_INCREASE_VALUE,
	KEYBIND_BIND_GLOBAL_NUMENTRY_DECREASE_VALUE,
	KEYBIND_BIND_GLOBAL_THUMBBAR_MIN_VALUE,
	KEYBIND_BIND_GLOBAL_THUMBBAR_MAX_VALUE,
	KEYBIND_BIND_GLOBAL_THUMBBAR_INCREASE_VALUE,
	KEYBIND_BIND_GLOBAL_THUMBBAR_INCREASE_VALUE_2X,
	KEYBIND_BIND_GLOBAL_THUMBBAR_INCREASE_VALUE_4X,
	KEYBIND_BIND_GLOBAL_THUMBBAR_INCREASE_VALUE_8X,
	KEYBIND_BIND_GLOBAL_THUMBBAR_DECREASE_VALUE,
	KEYBIND_BIND_GLOBAL_THUMBBAR_DECREASE_VALUE_2X,
	KEYBIND_BIND_GLOBAL_THUMBBAR_DECREASE_VALUE_4X,
	KEYBIND_BIND_GLOBAL_THUMBBAR_DECREASE_VALUE_8X,

	KEYBIND_BIND_GLOBAL_MAX_,
};

enum {
	/* *** DIALOG *** */
	KEYBIND_BIND_DIALOG_YES,
	KEYBIND_BIND_DIALOG_NO,
	KEYBIND_BIND_DIALOG_ANSWER_OK,
	KEYBIND_BIND_DIALOG_ANSWER_CANCEL,
	KEYBIND_BIND_DIALOG_CANCEL,
	KEYBIND_BIND_DIALOG_ACCEPT,

	KEYBIND_BIND_DIALOG_MAX_,
};

enum {
	/* *** NOTES *** */
	KEYBIND_BIND_NOTES_NOTE_ROW1_C,
	KEYBIND_BIND_NOTES_NOTE_ROW1_C_SHARP,
	KEYBIND_BIND_NOTES_NOTE_ROW1_D,
	KEYBIND_BIND_NOTES_NOTE_ROW1_D_SHARP,
	KEYBIND_BIND_NOTES_NOTE_ROW1_E,
	KEYBIND_BIND_NOTES_NOTE_ROW1_F,
	KEYBIND_BIND_NOTES_NOTE_ROW1_F_SHARP,
	KEYBIND_BIND_NOTES_NOTE_ROW1_G,
	KEYBIND_BIND_NOTES_NOTE_ROW1_G_SHARP,
	KEYBIND_BIND_NOTES_NOTE_ROW1_A,
	KEYBIND_BIND_NOTES_NOTE_ROW1_A_SHARP,
	KEYBIND_BIND_NOTES_NOTE_ROW1_B,
	KEYBIND_BIND_NOTES_NOTE_ROW2_C,
	KEYBIND_BIND_NOTES_NOTE_ROW2_C_SHARP,
	KEYBIND_BIND_NOTES_NOTE_ROW2_D,
	KEYBIND_BIND_NOTES_NOTE_ROW2_D_SHARP,
	KEYBIND_BIND_NOTES_NOTE_ROW2_E,
	KEYBIND_BIND_NOTES_NOTE_ROW2_F,
	KEYBIND_BIND_NOTES_NOTE_ROW2_F_SHARP,
	KEYBIND_BIND_NOTES_NOTE_ROW2_G,
	KEYBIND_BIND_NOTES_NOTE_ROW2_G_SHARP,
	KEYBIND_BIND_NOTES_NOTE_ROW2_A,
	KEYBIND_BIND_NOTES_NOTE_ROW2_A_SHARP,
	KEYBIND_BIND_NOTES_NOTE_ROW2_B,
	KEYBIND_BIND_NOTES_NOTE_ROW3_C,
	KEYBIND_BIND_NOTES_NOTE_ROW3_C_SHARP,
	KEYBIND_BIND_NOTES_NOTE_ROW3_D,
	KEYBIND_BIND_NOTES_NOTE_ROW3_D_SHARP,
	KEYBIND_BIND_NOTES_NOTE_ROW3_E,

	KEYBIND_BIND_NOTES_MAX_,
};

/* returns nonzero if there was an error */
int keybinds_init(void);

/* run on every event, and adjusts the state of the keybinds */
void keybinds_event(const struct key_event *kk);

/* get state of a specific keybind. */
int keybinds_pressed(int section, int bind);
int keybinds_released(int section, int bind);

/* was this keybind handled (pressed OR released?) */
int keybinds_handled(int section, int bind);

/* ------------------------------------------------------------------------ */
/* these next defines should generally be considered private implementation
 * details and shouldn't be messed with outside of keybinds.c and friends */

enum {
	KEYBIND_MOD_NONE = (0),

	/* Low 8 bytes: LCTRL, RCTRL, etc */
	KEYBIND_MOD_LCTRL = (0x01),
	KEYBIND_MOD_RCTRL = (0x02),
	KEYBIND_MOD_LSHIFT = (0x04),
	KEYBIND_MOD_RSHIFT = (0x08),
	KEYBIND_MOD_LALT = (0x10),
	KEYBIND_MOD_RALT = (0x20),
	/*
	KEYBIND_MOD_LGUI = (0x40),
	KEYBIND_MOD_RGUI = (0x80),
	*/

	/* Next 8 bytes: CTRL, SHIFT, ALT. Defined in a way to where mutual exclusion
	 * is easily calculated:
	 *
	 *     uint16_t x = (keybind_mods & 0xFFFF);
	 *
	 *     SCHISM_RUNTIME_ASSERT(((x >> 8) & x) != 0,
	 *       "left/right and full modifiers are mutually exclusive"); */
	KEYBIND_MOD_CTRL = ((KEYBIND_MOD_LCTRL | KEYBIND_MOD_RCTRL) << 8),
	KEYBIND_MOD_SHIFT = ((KEYBIND_MOD_LSHIFT | KEYBIND_MOD_RSHIFT) << 8),
	KEYBIND_MOD_ALT = ((KEYBIND_MOD_LALT | KEYBIND_MOD_RALT) << 8),
	/*
	KEYBIND_MOD_GUI = ((KEYBIND_MOD_LGUI | KEYBIND_MOD_RGUI) << 8),
	*/
};

int keybinds_parse_keycode(const char *name, schism_keysym_t *ret);
int keybinds_parse_scancode(const char *name, schism_scancode_t *ret);
int keybinds_parse_modkey(const char *name, uint16_t *ret);

#endif /* SCHISM_KEYBINDS_H_ */
