/*
 * Schism Tracker - a cross-platform Impulse Tracker clone
 * copyright (c) 2003-2005 Storlek <storlek@rigelseven.com>
 * copyright (c) 2005-2008 Mrs. Brisby <mrs.brisby@nimh.org>
 * copyright (c) 2009 Storlek & Mrs. Brisby
 * copyright (c) 2010-2012 Storlek
 * URL: http://schismtracker.org/
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

#include "it.h"
#include "util.h"
#include "charset.h"

#include "keybinds.h"

/* do NOT edit anything in this file, it's generated by `scripts/genkeybinds.py`.
 * edit that script and regenerate instead of editing this file */

int keybinds_parse_scancode(const char *name, schism_scancode_t *ret)
{
	char *casefolded_name = charset_case_fold(name, CHARSET_UTF8);
	uint32_t crc = crc32b(casefolded_name);
	free(casefolded_name);

	switch (crc) {
	case 0x2c8449ee: /* us_a */
		*ret = SCHISM_SCANCODE_A;
		return 1;
	case 0xb58d1854: /* us_b */
		*ret = SCHISM_SCANCODE_B;
		return 1;
	case 0xc28a28c2: /* us_c */
		*ret = SCHISM_SCANCODE_C;
		return 1;
	case 0x5ceebd61: /* us_d */
		*ret = SCHISM_SCANCODE_D;
		return 1;
	case 0x2be98df7: /* us_e */
		*ret = SCHISM_SCANCODE_E;
		return 1;
	case 0xb2e0dc4d: /* us_f */
		*ret = SCHISM_SCANCODE_F;
		return 1;
	case 0xc5e7ecdb: /* us_g */
		*ret = SCHISM_SCANCODE_G;
		return 1;
	case 0x5558f14a: /* us_h */
		*ret = SCHISM_SCANCODE_H;
		return 1;
	case 0x225fc1dc: /* us_i */
		*ret = SCHISM_SCANCODE_I;
		return 1;
	case 0xbb569066: /* us_j */
		*ret = SCHISM_SCANCODE_J;
		return 1;
	case 0xcc51a0f0: /* us_k */
		*ret = SCHISM_SCANCODE_K;
		return 1;
	case 0x52353553: /* us_l */
		*ret = SCHISM_SCANCODE_L;
		return 1;
	case 0x253205c5: /* us_m */
		*ret = SCHISM_SCANCODE_M;
		return 1;
	case 0xbc3b547f: /* us_n */
		*ret = SCHISM_SCANCODE_N;
		return 1;
	case 0xcb3c64e9: /* us_o */
		*ret = SCHISM_SCANCODE_O;
		return 1;
	case 0x4634691c: /* us_p */
		*ret = SCHISM_SCANCODE_P;
		return 1;
	case 0x3133598a: /* us_q */
		*ret = SCHISM_SCANCODE_Q;
		return 1;
	case 0xa83a0830: /* us_r */
		*ret = SCHISM_SCANCODE_R;
		return 1;
	case 0xdf3d38a6: /* us_s */
		*ret = SCHISM_SCANCODE_S;
		return 1;
	case 0x4159ad05: /* us_t */
		*ret = SCHISM_SCANCODE_T;
		return 1;
	case 0x365e9d93: /* us_u */
		*ret = SCHISM_SCANCODE_U;
		return 1;
	case 0xaf57cc29: /* us_v */
		*ret = SCHISM_SCANCODE_V;
		return 1;
	case 0xd850fcbf: /* us_w */
		*ret = SCHISM_SCANCODE_W;
		return 1;
	case 0x48efe12e: /* us_x */
		*ret = SCHISM_SCANCODE_X;
		return 1;
	case 0x3fe8d1b8: /* us_y */
		*ret = SCHISM_SCANCODE_Y;
		return 1;
	case 0xa6e18002: /* us_z */
		*ret = SCHISM_SCANCODE_Z;
		return 1;
	case 0x47ef181a: /* us_1 */
		*ret = SCHISM_SCANCODE_1;
		return 1;
	case 0xdee649a0: /* us_2 */
		*ret = SCHISM_SCANCODE_2;
		return 1;
	case 0xa9e17936: /* us_3 */
		*ret = SCHISM_SCANCODE_3;
		return 1;
	case 0x3785ec95: /* us_4 */
		*ret = SCHISM_SCANCODE_4;
		return 1;
	case 0x4082dc03: /* us_5 */
		*ret = SCHISM_SCANCODE_5;
		return 1;
	case 0xd98b8db9: /* us_6 */
		*ret = SCHISM_SCANCODE_6;
		return 1;
	case 0xae8cbd2f: /* us_7 */
		*ret = SCHISM_SCANCODE_7;
		return 1;
	case 0x3e33a0be: /* us_8 */
		*ret = SCHISM_SCANCODE_8;
		return 1;
	case 0x49349028: /* us_9 */
		*ret = SCHISM_SCANCODE_9;
		return 1;
	case 0x30e8288c: /* us_0 */
		*ret = SCHISM_SCANCODE_0;
		return 1;
	case 0x8b033246: /* us_f1 */
		*ret = SCHISM_SCANCODE_F1;
		return 1;
	case 0x120a63fc: /* us_f2 */
		*ret = SCHISM_SCANCODE_F2;
		return 1;
	case 0x650d536a: /* us_f3 */
		*ret = SCHISM_SCANCODE_F3;
		return 1;
	case 0xfb69c6c9: /* us_f4 */
		*ret = SCHISM_SCANCODE_F4;
		return 1;
	case 0x8c6ef65f: /* us_f5 */
		*ret = SCHISM_SCANCODE_F5;
		return 1;
	case 0x1567a7e5: /* us_f6 */
		*ret = SCHISM_SCANCODE_F6;
		return 1;
	case 0x62609773: /* us_f7 */
		*ret = SCHISM_SCANCODE_F7;
		return 1;
	case 0xf2df8ae2: /* us_f8 */
		*ret = SCHISM_SCANCODE_F8;
		return 1;
	case 0x85d8ba74: /* us_f9 */
		*ret = SCHISM_SCANCODE_F9;
		return 1;
	case 0x6bef38b6: /* us_f10 */
		*ret = SCHISM_SCANCODE_F10;
		return 1;
	case 0x1ce80820: /* us_f11 */
		*ret = SCHISM_SCANCODE_F11;
		return 1;
	case 0x85e1599a: /* us_f12 */
		*ret = SCHISM_SCANCODE_F12;
		return 1;
	case 0xbd2303b5: /* us_return */
		*ret = SCHISM_SCANCODE_RETURN;
		return 1;
	case 0xde98077a: /* us_enter */
		*ret = SCHISM_SCANCODE_RETURN;
		return 1;
	case 0x3f558c34: /* us_escape */
		*ret = SCHISM_SCANCODE_ESCAPE;
		return 1;
	case 0xb10a4f7d: /* us_backspace */
		*ret = SCHISM_SCANCODE_BACKSPACE;
		return 1;
	case 0x4b932224: /* us_tab */
		*ret = SCHISM_SCANCODE_TAB;
		return 1;
	case 0x4e9a062e: /* us_space */
		*ret = SCHISM_SCANCODE_SPACE;
		return 1;
	case 0x5f4b7063: /* us_minus */
		*ret = SCHISM_SCANCODE_MINUS;
		return 1;
	case 0x22443f1b: /* us_equals */
		*ret = SCHISM_SCANCODE_EQUALS;
		return 1;
	case 0x40a72447: /* us_leftbracket */
		*ret = SCHISM_SCANCODE_LEFTBRACKET;
		return 1;
	case 0x99ecfe03: /* us_rightbracket */
		*ret = SCHISM_SCANCODE_RIGHTBRACKET;
		return 1;
	case 0x9fb6c9b6: /* us_backslash */
		*ret = SCHISM_SCANCODE_BACKSLASH;
		return 1;
	case 0xc829187f: /* us_semicolon */
		*ret = SCHISM_SCANCODE_SEMICOLON;
		return 1;
	case 0xbe1920cc: /* us_apostrophe */
		*ret = SCHISM_SCANCODE_APOSTROPHE;
		return 1;
	case 0x464619f3: /* us_grave */
		*ret = SCHISM_SCANCODE_GRAVE;
		return 1;
	case 0xb6f4c696: /* us_comma */
		*ret = SCHISM_SCANCODE_COMMA;
		return 1;
	case 0xdf052274: /* us_period */
		*ret = SCHISM_SCANCODE_PERIOD;
		return 1;
	case 0x602680e5: /* us_slash */
		*ret = SCHISM_SCANCODE_SLASH;
		return 1;
	case 0x3459cca4: /* us_capslock */
		*ret = SCHISM_SCANCODE_CAPSLOCK;
		return 1;
	case 0xb930c753: /* us_printscreen */
		*ret = SCHISM_SCANCODE_PRINTSCREEN;
		return 1;
	case 0x7e19cb97: /* us_scrolllock */
		*ret = SCHISM_SCANCODE_SCROLLLOCK;
		return 1;
	case 0xb07255f9: /* us_pause */
		*ret = SCHISM_SCANCODE_PAUSE;
		return 1;
	case 0xdf71a24f: /* us_insert */
		*ret = SCHISM_SCANCODE_INSERT;
		return 1;
	case 0x20af403d: /* us_delete */
		*ret = SCHISM_SCANCODE_DELETE;
		return 1;
	case 0x445bd44b: /* us_home */
		*ret = SCHISM_SCANCODE_HOME;
		return 1;
	case 0x388c5299: /* us_end */
		*ret = SCHISM_SCANCODE_END;
		return 1;
	case 0xeeaff4db: /* us_pageup */
		*ret = SCHISM_SCANCODE_PAGEUP;
		return 1;
	case 0xac6ea158: /* us_pagedown */
		*ret = SCHISM_SCANCODE_PAGEDOWN;
		return 1;
	case 0xd322b200: /* us_right */
		*ret = SCHISM_SCANCODE_RIGHT;
		return 1;
	case 0x4fea3ff3: /* us_left */
		*ret = SCHISM_SCANCODE_LEFT;
		return 1;
	case 0x297248a0: /* us_down */
		*ret = SCHISM_SCANCODE_DOWN;
		return 1;
	case 0xeb3702d2: /* us_up */
		*ret = SCHISM_SCANCODE_UP;
		return 1;
	case 0x7891b220: /* us_numlockclear */
		*ret = SCHISM_SCANCODE_NUMLOCKCLEAR;
		return 1;
	case 0x7d44a2e0: /* us_kp_divide */
		*ret = SCHISM_SCANCODE_KP_DIVIDE;
		return 1;
	case 0xaa6595b9: /* us_kp_multiply */
		*ret = SCHISM_SCANCODE_KP_MULTIPLY;
		return 1;
	case 0x36d769ef: /* us_kp_minus */
		*ret = SCHISM_SCANCODE_KP_MINUS;
		return 1;
	case 0x3fa44af9: /* us_kp_plus */
		*ret = SCHISM_SCANCODE_KP_PLUS;
		return 1;
	case 0xb7041ef6: /* us_kp_enter */
		*ret = SCHISM_SCANCODE_KP_ENTER;
		return 1;
	case 0xc0e25e74: /* us_kp_1 */
		*ret = SCHISM_SCANCODE_KP_1;
		return 1;
	case 0x59eb0fce: /* us_kp_2 */
		*ret = SCHISM_SCANCODE_KP_2;
		return 1;
	case 0x2eec3f58: /* us_kp_3 */
		*ret = SCHISM_SCANCODE_KP_3;
		return 1;
	case 0xb088aafb: /* us_kp_4 */
		*ret = SCHISM_SCANCODE_KP_4;
		return 1;
	case 0xc78f9a6d: /* us_kp_5 */
		*ret = SCHISM_SCANCODE_KP_5;
		return 1;
	case 0x5e86cbd7: /* us_kp_6 */
		*ret = SCHISM_SCANCODE_KP_6;
		return 1;
	case 0x2981fb41: /* us_kp_7 */
		*ret = SCHISM_SCANCODE_KP_7;
		return 1;
	case 0xb93ee6d0: /* us_kp_8 */
		*ret = SCHISM_SCANCODE_KP_8;
		return 1;
	case 0xce39d646: /* us_kp_9 */
		*ret = SCHISM_SCANCODE_KP_9;
		return 1;
	case 0xb7e56ee2: /* us_kp_0 */
		*ret = SCHISM_SCANCODE_KP_0;
		return 1;
	case 0x3b627166: /* us_kp_period */
		*ret = SCHISM_SCANCODE_KP_PERIOD;
		return 1;
	case 0xc6236c09: /* us_kp_equals */
		*ret = SCHISM_SCANCODE_KP_EQUALS;
		return 1;
	default:
		break;
	}

	*ret = SCHISM_SCANCODE_UNKNOWN;
	return 0;
}

int keybinds_parse_modkey(const char *name, uint16_t *ret)
{
	char *casefolded_name = charset_case_fold(name, CHARSET_UTF8);
	uint32_t crc = crc32b(casefolded_name);
	free(casefolded_name);

	switch (crc) {
	case 0x0222717a: /* ctrl */
		*ret = KEYBIND_MOD_CTRL;
		return 1;
	case 0xb986c337: /* lctrl */
		*ret = KEYBIND_MOD_LCTRL;
		return 1;
	case 0x6656ead4: /* rctrl */
		*ret = KEYBIND_MOD_RCTRL;
		return 1;
	case 0xa50b3b45: /* shift */
		*ret = KEYBIND_MOD_SHIFT;
		return 1;
	case 0xaddda2da: /* lshift */
		*ret = KEYBIND_MOD_LSHIFT;
		return 1;
	case 0x9401c131: /* rshift */
		*ret = KEYBIND_MOD_RSHIFT;
		return 1;
	case 0x2874e98b: /* alt */
		*ret = KEYBIND_MOD_ALT;
		return 1;
	case 0x8781a73e: /* lalt */
		*ret = KEYBIND_MOD_LALT;
		return 1;
	case 0x37478792: /* ralt */
		*ret = KEYBIND_MOD_RALT;
		return 1;
	default:
		break;
	}

	*ret = KEYBIND_MOD_NONE;
	return 0;
}

int keybinds_parse_keycode(const char *name, schism_keysym_t *ret)
{
	char *casefolded_name = charset_case_fold(name, CHARSET_UTF8);
	uint32_t crc = crc32b(casefolded_name);
	free(casefolded_name);

	switch (crc) {
	case 0xa79e3f0f: /* return */
		*ret = SCHISM_KEYSYM_RETURN;
		return 1;
	case 0xb970c06e: /* enter */
		*ret = SCHISM_KEYSYM_RETURN;
		return 1;
	case 0x25e8b08e: /* escape */
		*ret = SCHISM_KEYSYM_ESCAPE;
		return 1;
	case 0xbfe0826f: /* backspace */
		*ret = SCHISM_KEYSYM_BACKSPACE;
		return 1;
	case 0x73e3430c: /* tab */
		*ret = SCHISM_KEYSYM_TAB;
		return 1;
	case 0x2972c13a: /* space */
		*ret = SCHISM_KEYSYM_SPACE;
		return 1;
	case 0xc2d81aaa: /* exclaim */
		*ret = SCHISM_KEYSYM_EXCLAIM;
		return 1;
	case 0x1e910af0: /* quotedbl */
		*ret = SCHISM_KEYSYM_QUOTEDBL;
		return 1;
	case 0xd1b862b8: /* hash */
		*ret = SCHISM_KEYSYM_HASH;
		return 1;
	case 0x61b68039: /* percent */
		*ret = SCHISM_KEYSYM_PERCENT;
		return 1;
	case 0xcb153c7a: /* dollar */
		*ret = SCHISM_KEYSYM_DOLLAR;
		return 1;
	case 0x50828443: /* ampersand */
		*ret = SCHISM_KEYSYM_AMPERSAND;
		return 1;
	case 0x6b71cbf4: /* quote */
		*ret = SCHISM_KEYSYM_QUOTE;
		return 1;
	case 0x233de1e3: /* leftparen */
		*ret = SCHISM_KEYSYM_LEFTPAREN;
		return 1;
	case 0x8c8ff1f1: /* rightparen */
		*ret = SCHISM_KEYSYM_RIGHTPAREN;
		return 1;
	case 0x3dc0084d: /* asterisk */
		*ret = SCHISM_KEYSYM_ASTERISK;
		return 1;
	case 0x90f2e0f1: /* plus */
		*ret = SCHISM_KEYSYM_PLUS;
		return 1;
	case 0xd11c0182: /* comma */
		*ret = SCHISM_KEYSYM_COMMA;
		return 1;
	case 0x38a3b777: /* minus */
		*ret = SCHISM_KEYSYM_MINUS;
		return 1;
	case 0xc5b81ece: /* period */
		*ret = SCHISM_KEYSYM_PERIOD;
		return 1;
	case 0x07ce47f1: /* slash */
		*ret = SCHISM_KEYSYM_SLASH;
		return 1;
	case 0xf4dbdf21: /* 0 */
		*ret = SCHISM_KEYSYM_0;
		return 1;
	case 0x83dcefb7: /* 1 */
		*ret = SCHISM_KEYSYM_1;
		return 1;
	case 0x1ad5be0d: /* 2 */
		*ret = SCHISM_KEYSYM_2;
		return 1;
	case 0x6dd28e9b: /* 3 */
		*ret = SCHISM_KEYSYM_3;
		return 1;
	case 0xf3b61b38: /* 4 */
		*ret = SCHISM_KEYSYM_4;
		return 1;
	case 0x84b12bae: /* 5 */
		*ret = SCHISM_KEYSYM_5;
		return 1;
	case 0x1db87a14: /* 6 */
		*ret = SCHISM_KEYSYM_6;
		return 1;
	case 0x6abf4a82: /* 7 */
		*ret = SCHISM_KEYSYM_7;
		return 1;
	case 0xfa005713: /* 8 */
		*ret = SCHISM_KEYSYM_8;
		return 1;
	case 0x8d076785: /* 9 */
		*ret = SCHISM_KEYSYM_9;
		return 1;
	case 0x725714a6: /* colon */
		*ret = SCHISM_KEYSYM_COLON;
		return 1;
	case 0xc6c3d56d: /* semicolon */
		*ret = SCHISM_KEYSYM_SEMICOLON;
		return 1;
	case 0xd3b694df: /* less */
		*ret = SCHISM_KEYSYM_LESS;
		return 1;
	case 0x38f903a1: /* equals */
		*ret = SCHISM_KEYSYM_EQUALS;
		return 1;
	case 0xb2a626fa: /* greater */
		*ret = SCHISM_KEYSYM_GREATER;
		return 1;
	case 0xb6f7494e: /* question */
		*ret = SCHISM_KEYSYM_QUESTION;
		return 1;
	case 0x6a57fd3c: /* at */
		*ret = SCHISM_KEYSYM_AT;
		return 1;
	case 0xdd86e473: /* leftbracket */
		*ret = SCHISM_KEYSYM_LEFTBRACKET;
		return 1;
	case 0x915c04a4: /* backslash */
		*ret = SCHISM_KEYSYM_BACKSLASH;
		return 1;
	case 0xb8c52b76: /* rightbracket */
		*ret = SCHISM_KEYSYM_RIGHTBRACKET;
		return 1;
	case 0x83bdfc1f: /* caret */
		*ret = SCHISM_KEYSYM_CARET;
		return 1;
	case 0x5835dd19: /* underscore */
		*ret = SCHISM_KEYSYM_UNDERSCORE;
		return 1;
	case 0xfde388a1: /* backquote */
		*ret = SCHISM_KEYSYM_BACKQUOTE;
		return 1;
	case 0xe8b7be43: /* a */
		*ret = SCHISM_KEYSYM_a;
		return 1;
	case 0x71beeff9: /* b */
		*ret = SCHISM_KEYSYM_b;
		return 1;
	case 0x06b9df6f: /* c */
		*ret = SCHISM_KEYSYM_c;
		return 1;
	case 0x98dd4acc: /* d */
		*ret = SCHISM_KEYSYM_d;
		return 1;
	case 0xefda7a5a: /* e */
		*ret = SCHISM_KEYSYM_e;
		return 1;
	case 0x76d32be0: /* f */
		*ret = SCHISM_KEYSYM_f;
		return 1;
	case 0x01d41b76: /* g */
		*ret = SCHISM_KEYSYM_g;
		return 1;
	case 0x916b06e7: /* h */
		*ret = SCHISM_KEYSYM_h;
		return 1;
	case 0xe66c3671: /* i */
		*ret = SCHISM_KEYSYM_i;
		return 1;
	case 0x7f6567cb: /* j */
		*ret = SCHISM_KEYSYM_j;
		return 1;
	case 0x0862575d: /* k */
		*ret = SCHISM_KEYSYM_k;
		return 1;
	case 0x9606c2fe: /* l */
		*ret = SCHISM_KEYSYM_l;
		return 1;
	case 0xe101f268: /* m */
		*ret = SCHISM_KEYSYM_m;
		return 1;
	case 0x7808a3d2: /* n */
		*ret = SCHISM_KEYSYM_n;
		return 1;
	case 0x0f0f9344: /* o */
		*ret = SCHISM_KEYSYM_o;
		return 1;
	case 0x82079eb1: /* p */
		*ret = SCHISM_KEYSYM_p;
		return 1;
	case 0xf500ae27: /* q */
		*ret = SCHISM_KEYSYM_q;
		return 1;
	case 0x6c09ff9d: /* r */
		*ret = SCHISM_KEYSYM_r;
		return 1;
	case 0x1b0ecf0b: /* s */
		*ret = SCHISM_KEYSYM_s;
		return 1;
	case 0x856a5aa8: /* t */
		*ret = SCHISM_KEYSYM_t;
		return 1;
	case 0xf26d6a3e: /* u */
		*ret = SCHISM_KEYSYM_u;
		return 1;
	case 0x6b643b84: /* v */
		*ret = SCHISM_KEYSYM_v;
		return 1;
	case 0x1c630b12: /* w */
		*ret = SCHISM_KEYSYM_w;
		return 1;
	case 0x8cdc1683: /* x */
		*ret = SCHISM_KEYSYM_x;
		return 1;
	case 0xfbdb2615: /* y */
		*ret = SCHISM_KEYSYM_y;
		return 1;
	case 0x62d277af: /* z */
		*ret = SCHISM_KEYSYM_z;
		return 1;
	case 0x051cecac: /* capslock */
		*ret = SCHISM_KEYSYM_CAPSLOCK;
		return 1;
	case 0x23a0dee4: /* f1 */
		*ret = SCHISM_KEYSYM_F1;
		return 1;
	case 0xbaa98f5e: /* f2 */
		*ret = SCHISM_KEYSYM_F2;
		return 1;
	case 0xcdaebfc8: /* f3 */
		*ret = SCHISM_KEYSYM_F3;
		return 1;
	case 0x53ca2a6b: /* f4 */
		*ret = SCHISM_KEYSYM_F4;
		return 1;
	case 0x24cd1afd: /* f5 */
		*ret = SCHISM_KEYSYM_F5;
		return 1;
	case 0xbdc44b47: /* f6 */
		*ret = SCHISM_KEYSYM_F6;
		return 1;
	case 0xcac37bd1: /* f7 */
		*ret = SCHISM_KEYSYM_F7;
		return 1;
	case 0x5a7c6640: /* f8 */
		*ret = SCHISM_KEYSYM_F8;
		return 1;
	case 0x2d7b56d6: /* f9 */
		*ret = SCHISM_KEYSYM_F9;
		return 1;
	case 0x539f599e: /* f10 */
		*ret = SCHISM_KEYSYM_F10;
		return 1;
	case 0x24986908: /* f11 */
		*ret = SCHISM_KEYSYM_F11;
		return 1;
	case 0xbd9138b2: /* f12 */
		*ret = SCHISM_KEYSYM_F12;
		return 1;
	case 0x24110767: /* printscreen */
		*ret = SCHISM_KEYSYM_PRINTSCREEN;
		return 1;
	case 0x8dae5012: /* scrolllock */
		*ret = SCHISM_KEYSYM_SCROLLLOCK;
		return 1;
	case 0xd79a92ed: /* pause */
		*ret = SCHISM_KEYSYM_PAUSE;
		return 1;
	case 0xc5cc9ef5: /* insert */
		*ret = SCHISM_KEYSYM_INSERT;
		return 1;
	case 0x71d60cd0: /* home */
		*ret = SCHISM_KEYSYM_HOME;
		return 1;
	case 0xf412c861: /* pageup */
		*ret = SCHISM_KEYSYM_PAGEUP;
		return 1;
	case 0x3a127c87: /* delete */
		*ret = SCHISM_KEYSYM_DELETE;
		return 1;
	case 0x00fc33b1: /* end */
		*ret = SCHISM_KEYSYM_END;
		return 1;
	case 0x9d2b8150: /* pagedown */
		*ret = SCHISM_KEYSYM_PAGEDOWN;
		return 1;
	case 0xb4ca7514: /* right */
		*ret = SCHISM_KEYSYM_RIGHT;
		return 1;
	case 0x7a67e768: /* left */
		*ret = SCHISM_KEYSYM_LEFT;
		return 1;
	case 0x1cff903b: /* down */
		*ret = SCHISM_KEYSYM_DOWN;
		return 1;
	case 0x4394ee70: /* up */
		*ret = SCHISM_KEYSYM_UP;
		return 1;
	case 0x59b86755: /* numlockclear */
		*ret = SCHISM_KEYSYM_NUMLOCKCLEAR;
		return 1;
	case 0x73ae6ff2: /* kp_divide */
		*ret = SCHISM_KEYSYM_KP_DIVIDE;
		return 1;
	case 0x3744558d: /* kp_multiply */
		*ret = SCHISM_KEYSYM_KP_MULTIPLY;
		return 1;
	case 0x079249e7: /* kp_minus */
		*ret = SCHISM_KEYSYM_KP_MINUS;
		return 1;
	case 0x140aad57: /* kp_plus */
		*ret = SCHISM_KEYSYM_KP_PLUS;
		return 1;
	case 0x86413efe: /* kp_enter */
		*ret = SCHISM_KEYSYM_KP_ENTER;
		return 1;
	case 0xf56f86ef: /* kp_1 */
		*ret = SCHISM_KEYSYM_KP_1;
		return 1;
	case 0x6c66d755: /* kp_2 */
		*ret = SCHISM_KEYSYM_KP_2;
		return 1;
	case 0x1b61e7c3: /* kp_3 */
		*ret = SCHISM_KEYSYM_KP_3;
		return 1;
	case 0x85057260: /* kp_4 */
		*ret = SCHISM_KEYSYM_KP_4;
		return 1;
	case 0xf20242f6: /* kp_5 */
		*ret = SCHISM_KEYSYM_KP_5;
		return 1;
	case 0x6b0b134c: /* kp_6 */
		*ret = SCHISM_KEYSYM_KP_6;
		return 1;
	case 0x1c0c23da: /* kp_7 */
		*ret = SCHISM_KEYSYM_KP_7;
		return 1;
	case 0x8cb33e4b: /* kp_8 */
		*ret = SCHISM_KEYSYM_KP_8;
		return 1;
	case 0xfbb40edd: /* kp_9 */
		*ret = SCHISM_KEYSYM_KP_9;
		return 1;
	case 0x8268b679: /* kp_0 */
		*ret = SCHISM_KEYSYM_KP_0;
		return 1;
	case 0x3588bc74: /* kp_period */
		*ret = SCHISM_KEYSYM_KP_PERIOD;
		return 1;
	case 0xa45bddc1: /* application */
		*ret = SCHISM_KEYSYM_APPLICATION;
		return 1;
	case 0xab8a01a0: /* power */
		*ret = SCHISM_KEYSYM_POWER;
		return 1;
	case 0xc8c9a11b: /* kp_equals */
		*ret = SCHISM_KEYSYM_KP_EQUALS;
		return 1;
	case 0xca960824: /* f13 */
		*ret = SCHISM_KEYSYM_F13;
		return 1;
	case 0x54f29d87: /* f14 */
		*ret = SCHISM_KEYSYM_F14;
		return 1;
	case 0x23f5ad11: /* f15 */
		*ret = SCHISM_KEYSYM_F15;
		return 1;
	case 0xbafcfcab: /* f16 */
		*ret = SCHISM_KEYSYM_F16;
		return 1;
	case 0xcdfbcc3d: /* f17 */
		*ret = SCHISM_KEYSYM_F17;
		return 1;
	case 0x5d44d1ac: /* f18 */
		*ret = SCHISM_KEYSYM_F18;
		return 1;
	case 0x2a43e13a: /* f19 */
		*ret = SCHISM_KEYSYM_F19;
		return 1;
	case 0x78b20a5d: /* f20 */
		*ret = SCHISM_KEYSYM_F20;
		return 1;
	case 0x0fb53acb: /* f21 */
		*ret = SCHISM_KEYSYM_F21;
		return 1;
	case 0x96bc6b71: /* f22 */
		*ret = SCHISM_KEYSYM_F22;
		return 1;
	case 0xe1bb5be7: /* f23 */
		*ret = SCHISM_KEYSYM_F23;
		return 1;
	case 0x7fdfce44: /* f24 */
		*ret = SCHISM_KEYSYM_F24;
		return 1;
	case 0xff6310de: /* execute */
		*ret = SCHISM_KEYSYM_EXECUTE;
		return 1;
	case 0x08875cac: /* help */
		*ret = SCHISM_KEYSYM_HELP;
		return 1;
	case 0x7d053a93: /* menu */
		*ret = SCHISM_KEYSYM_MENU;
		return 1;
	case 0x4bf2eac0: /* select */
		*ret = SCHISM_KEYSYM_SELECT;
		return 1;
	case 0xb95616b6: /* stop */
		*ret = SCHISM_KEYSYM_STOP;
		return 1;
	case 0x93a15bfc: /* again */
		*ret = SCHISM_KEYSYM_AGAIN;
		return 1;
	case 0xe370bbf2: /* undo */
		*ret = SCHISM_KEYSYM_UNDO;
		return 1;
	case 0xb0f094fd: /* cut */
		*ret = SCHISM_KEYSYM_CUT;
		return 1;
	case 0x4dbabb82: /* copy */
		*ret = SCHISM_KEYSYM_COPY;
		return 1;
	case 0x9c567898: /* paste */
		*ret = SCHISM_KEYSYM_PASTE;
		return 1;
	case 0xc9ae6404: /* find */
		*ret = SCHISM_KEYSYM_FIND;
		return 1;
	case 0xccb9735c: /* mute */
		*ret = SCHISM_KEYSYM_MUTE;
		return 1;
	case 0xb9fa0176: /* volumeup */
		*ret = SCHISM_KEYSYM_VOLUMEUP;
		return 1;
	case 0x7a10323a: /* volumedown */
		*ret = SCHISM_KEYSYM_VOLUMEDOWN;
		return 1;
	case 0xee2dff12: /* kp_comma */
		*ret = SCHISM_KEYSYM_KP_COMMA;
		return 1;
	case 0xbebdc5fb: /* kp_equalsas400 */
		*ret = SCHISM_KEYSYM_KP_EQUALSAS400;
		return 1;
	case 0x45fd98d5: /* alterase */
		*ret = SCHISM_KEYSYM_ALTERASE;
		return 1;
	case 0xd9c13176: /* sysreq */
		*ret = SCHISM_KEYSYM_SYSREQ;
		return 1;
	case 0x5616c572: /* cancel */
		*ret = SCHISM_KEYSYM_CANCEL;
		return 1;
	case 0xe5b1f106: /* clear */
		*ret = SCHISM_KEYSYM_CLEAR;
		return 1;
	case 0xe5aee812: /* prior */
		*ret = SCHISM_KEYSYM_PRIOR;
		return 1;
	case 0x8acd3da3: /* return2 */
		*ret = SCHISM_KEYSYM_RETURN2;
		return 1;
	case 0x97f2cd88: /* separator */
		*ret = SCHISM_KEYSYM_SEPARATOR;
		return 1;
	case 0xb9ea6d99: /* out */
		*ret = SCHISM_KEYSYM_OUT;
		return 1;
	case 0xb071dfeb: /* oper */
		*ret = SCHISM_KEYSYM_OPER;
		return 1;
	case 0xc5ae4c10: /* clearagain */
		*ret = SCHISM_KEYSYM_CLEARAGAIN;
		return 1;
	case 0xd3bff60f: /* crsel */
		*ret = SCHISM_KEYSYM_CRSEL;
		return 1;
	case 0x3342e3cb: /* exsel */
		*ret = SCHISM_KEYSYM_EXSEL;
		return 1;
	case 0xdd807e0f: /* kp_00 */
		*ret = SCHISM_KEYSYM_KP_00;
		return 1;
	case 0x64b942ce: /* kp_000 */
		*ret = SCHISM_KEYSYM_KP_000;
		return 1;
	case 0xbade325d: /* thousandsseparator */
		*ret = SCHISM_KEYSYM_THOUSANDSSEPARATOR;
		return 1;
	case 0x942f12bf: /* decimalseparator */
		*ret = SCHISM_KEYSYM_DECIMALSEPARATOR;
		return 1;
	case 0x435a8db2: /* currencyunit */
		*ret = SCHISM_KEYSYM_CURRENCYUNIT;
		return 1;
	case 0x58bbbf34: /* currencysubunit */
		*ret = SCHISM_KEYSYM_CURRENCYSUBUNIT;
		return 1;
	case 0x511c7412: /* kp_leftparen */
		*ret = SCHISM_KEYSYM_KP_LEFTPAREN;
		return 1;
	case 0x464712ee: /* kp_rightparen */
		*ret = SCHISM_KEYSYM_KP_RIGHTPAREN;
		return 1;
	case 0xd6782ba6: /* kp_leftbrace */
		*ret = SCHISM_KEYSYM_KP_LEFTBRACE;
		return 1;
	case 0xc1234d5a: /* kp_rightbrace */
		*ret = SCHISM_KEYSYM_KP_RIGHTBRACE;
		return 1;
	case 0x35ef3b1f: /* kp_tab */
		*ret = SCHISM_KEYSYM_KP_TAB;
		return 1;
	case 0xcdc1179e: /* kp_backspace */
		*ret = SCHISM_KEYSYM_KP_BACKSPACE;
		return 1;
	case 0x9e04d71b: /* kp_a */
		*ret = SCHISM_KEYSYM_KP_A;
		return 1;
	case 0x070d86a1: /* kp_b */
		*ret = SCHISM_KEYSYM_KP_B;
		return 1;
	case 0x700ab637: /* kp_c */
		*ret = SCHISM_KEYSYM_KP_C;
		return 1;
	case 0xee6e2394: /* kp_d */
		*ret = SCHISM_KEYSYM_KP_D;
		return 1;
	case 0x99691302: /* kp_e */
		*ret = SCHISM_KEYSYM_KP_E;
		return 1;
	case 0x006042b8: /* kp_f */
		*ret = SCHISM_KEYSYM_KP_F;
		return 1;
	case 0xbfc1ff91: /* kp_xor */
		*ret = SCHISM_KEYSYM_KP_XOR;
		return 1;
	case 0x94bbff30: /* kp_power */
		*ret = SCHISM_KEYSYM_KP_POWER;
		return 1;
	case 0x4af2ea09: /* kp_percent */
		*ret = SCHISM_KEYSYM_KP_PERCENT;
		return 1;
	case 0x574ed979: /* kp_less */
		*ret = SCHISM_KEYSYM_KP_LESS;
		return 1;
	case 0x99e24cca: /* kp_greater */
		*ret = SCHISM_KEYSYM_KP_GREATER;
		return 1;
	case 0x22a311b2: /* kp_ampersand */
		*ret = SCHISM_KEYSYM_KP_AMPERSAND;
		return 1;
	case 0xd130bd66: /* kp_dblampersand */
		*ret = SCHISM_KEYSYM_KP_DBLAMPERSAND;
		return 1;
	case 0xfd01607b: /* kp_verticalbar */
		*ret = SCHISM_KEYSYM_KP_VERTICALBAR;
		return 1;
	case 0xc7357c30: /* kp_dblverticalbar */
		*ret = SCHISM_KEYSYM_KP_DBLVERTICALBAR;
		return 1;
	case 0x4d66ea36: /* kp_colon */
		*ret = SCHISM_KEYSYM_KP_COLON;
		return 1;
	case 0x55402f1e: /* kp_hash */
		*ret = SCHISM_KEYSYM_KP_HASH;
		return 1;
	case 0x16433faa: /* kp_space */
		*ret = SCHISM_KEYSYM_KP_SPACE;
		return 1;
	case 0x0f919793: /* kp_at */
		*ret = SCHISM_KEYSYM_KP_AT;
		return 1;
	case 0xf7d21b54: /* kp_exclam */
		*ret = SCHISM_KEYSYM_KP_EXCLAM;
		return 1;
	case 0x5cafce69: /* kp_memstore */
		*ret = SCHISM_KEYSYM_KP_MEMSTORE;
		return 1;
	case 0xb19cc083: /* kp_memrecall */
		*ret = SCHISM_KEYSYM_KP_MEMRECALL;
		return 1;
	case 0x46496718: /* kp_memclear */
		*ret = SCHISM_KEYSYM_KP_MEMCLEAR;
		return 1;
	case 0x6f5d628b: /* kp_memadd */
		*ret = SCHISM_KEYSYM_KP_MEMADD;
		return 1;
	case 0xa39dc3e2: /* kp_memsubtract */
		*ret = SCHISM_KEYSYM_KP_MEMSUBTRACT;
		return 1;
	case 0x9373f820: /* kp_memmultiply */
		*ret = SCHISM_KEYSYM_KP_MEMMULTIPLY;
		return 1;
	case 0x793208bd: /* kp_memdivide */
		*ret = SCHISM_KEYSYM_KP_MEMDIVIDE;
		return 1;
	case 0x2ea837f7: /* kp_plusminus */
		*ret = SCHISM_KEYSYM_KP_PLUSMINUS;
		return 1;
	case 0xda800f96: /* kp_clear */
		*ret = SCHISM_KEYSYM_KP_CLEAR;
		return 1;
	case 0xb7e66983: /* kp_clearentry */
		*ret = SCHISM_KEYSYM_KP_CLEARENTRY;
		return 1;
	case 0x36d04bbf: /* kp_binary */
		*ret = SCHISM_KEYSYM_KP_BINARY;
		return 1;
	case 0xa0f806e5: /* kp_octal */
		*ret = SCHISM_KEYSYM_KP_OCTAL;
		return 1;
	case 0x71b9d9a3: /* kp_decimal */
		*ret = SCHISM_KEYSYM_KP_DECIMAL;
		return 1;
	case 0xab3761b6: /* kp_hexadecimal */
		*ret = SCHISM_KEYSYM_KP_HEXADECIMAL;
		return 1;
	case 0xcbcc3ee1: /* rgui */
		*ret = SCHISM_KEYSYM_RGUI;
		return 1;
	default:
		break;
	}

	*ret = SCHISM_KEYSYM_UNKNOWN;
	return 0;
}

