/*
 * Schism Tracker - a cross-platform Impulse Tracker clone
 * copyright (c) 2003-2005 Storlek <storlek@rigelseven.com>
 * copyright (c) 2005-2008 Mrs. Brisby <mrs.brisby@nimh.org>
 * copyright (c) 2009 Storlek & Mrs. Brisby
 * copyright (c) 2010-2012 Storlek
 * URL: http://schismtracker.org/
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

#include "it.h"
#include "util.h"

/* do NOT edit anything in this file, it's generated by `scripts/genkeybinds.py`.
 * edit that script and regenerate instead of editing this file */

int keybinds_parse_scancode(const char *name, SDL_Scancode *ret)
{
	switch (crc32b(name)) {
	case 0x8f9580f8: /* US_A */
		*ret = SDL_SCANCODE_A;
		return 1;
	case 0x169cd142: /* US_B */
		*ret = SDL_SCANCODE_B;
		return 1;
	case 0x619be1d4: /* US_C */
		*ret = SDL_SCANCODE_C;
		return 1;
	case 0xffff7477: /* US_D */
		*ret = SDL_SCANCODE_D;
		return 1;
	case 0x88f844e1: /* US_E */
		*ret = SDL_SCANCODE_E;
		return 1;
	case 0x11f1155b: /* US_F */
		*ret = SDL_SCANCODE_F;
		return 1;
	case 0x66f625cd: /* US_G */
		*ret = SDL_SCANCODE_G;
		return 1;
	case 0xf649385c: /* US_H */
		*ret = SDL_SCANCODE_H;
		return 1;
	case 0x814e08ca: /* US_I */
		*ret = SDL_SCANCODE_I;
		return 1;
	case 0x18475970: /* US_J */
		*ret = SDL_SCANCODE_J;
		return 1;
	case 0x6f4069e6: /* US_K */
		*ret = SDL_SCANCODE_K;
		return 1;
	case 0xf124fc45: /* US_L */
		*ret = SDL_SCANCODE_L;
		return 1;
	case 0x8623ccd3: /* US_M */
		*ret = SDL_SCANCODE_M;
		return 1;
	case 0x1f2a9d69: /* US_N */
		*ret = SDL_SCANCODE_N;
		return 1;
	case 0x682dadff: /* US_O */
		*ret = SDL_SCANCODE_O;
		return 1;
	case 0xe525a00a: /* US_P */
		*ret = SDL_SCANCODE_P;
		return 1;
	case 0x9222909c: /* US_Q */
		*ret = SDL_SCANCODE_Q;
		return 1;
	case 0x0b2bc126: /* US_R */
		*ret = SDL_SCANCODE_R;
		return 1;
	case 0x7c2cf1b0: /* US_S */
		*ret = SDL_SCANCODE_S;
		return 1;
	case 0xe2486413: /* US_T */
		*ret = SDL_SCANCODE_T;
		return 1;
	case 0x954f5485: /* US_U */
		*ret = SDL_SCANCODE_U;
		return 1;
	case 0x0c46053f: /* US_V */
		*ret = SDL_SCANCODE_V;
		return 1;
	case 0x7b4135a9: /* US_W */
		*ret = SDL_SCANCODE_W;
		return 1;
	case 0xebfe2838: /* US_X */
		*ret = SDL_SCANCODE_X;
		return 1;
	case 0x9cf918ae: /* US_Y */
		*ret = SDL_SCANCODE_Y;
		return 1;
	case 0x05f04914: /* US_Z */
		*ret = SDL_SCANCODE_Z;
		return 1;
	case 0xdf90f1c4: /* US_1 */
		*ret = SDL_SCANCODE_1;
		return 1;
	case 0x4699a07e: /* US_2 */
		*ret = SDL_SCANCODE_2;
		return 1;
	case 0x319e90e8: /* US_3 */
		*ret = SDL_SCANCODE_3;
		return 1;
	case 0xaffa054b: /* US_4 */
		*ret = SDL_SCANCODE_4;
		return 1;
	case 0xd8fd35dd: /* US_5 */
		*ret = SDL_SCANCODE_5;
		return 1;
	case 0x41f46467: /* US_6 */
		*ret = SDL_SCANCODE_6;
		return 1;
	case 0x36f354f1: /* US_7 */
		*ret = SDL_SCANCODE_7;
		return 1;
	case 0xa64c4960: /* US_8 */
		*ret = SDL_SCANCODE_8;
		return 1;
	case 0xd14b79f6: /* US_9 */
		*ret = SDL_SCANCODE_9;
		return 1;
	case 0xa897c152: /* US_0 */
		*ret = SDL_SCANCODE_0;
		return 1;
	case 0x7f7496de: /* US_F1 */
		*ret = SDL_SCANCODE_F1;
		return 1;
	case 0xe67dc764: /* US_F2 */
		*ret = SDL_SCANCODE_F2;
		return 1;
	case 0x917af7f2: /* US_F3 */
		*ret = SDL_SCANCODE_F3;
		return 1;
	case 0x0f1e6251: /* US_F4 */
		*ret = SDL_SCANCODE_F4;
		return 1;
	case 0x781952c7: /* US_F5 */
		*ret = SDL_SCANCODE_F5;
		return 1;
	case 0xe110037d: /* US_F6 */
		*ret = SDL_SCANCODE_F6;
		return 1;
	case 0x961733eb: /* US_F7 */
		*ret = SDL_SCANCODE_F7;
		return 1;
	case 0x06a82e7a: /* US_F8 */
		*ret = SDL_SCANCODE_F8;
		return 1;
	case 0x71af1eec: /* US_F9 */
		*ret = SDL_SCANCODE_F9;
		return 1;
	case 0x95cf5464: /* US_F10 */
		*ret = SDL_SCANCODE_F10;
		return 1;
	case 0xe2c864f2: /* US_F11 */
		*ret = SDL_SCANCODE_F11;
		return 1;
	case 0x7bc13548: /* US_F12 */
		*ret = SDL_SCANCODE_F12;
		return 1;
	case 0x365c24c6: /* US_RETURN */
		*ret = SDL_SCANCODE_RETURN;
		return 1;
	case 0xb42aab47: /* US_ESCAPE */
		*ret = SDL_SCANCODE_ESCAPE;
		return 1;
	case 0x6b6505bd: /* US_BACKSPACE */
		*ret = SDL_SCANCODE_BACKSPACE;
		return 1;
	case 0x1b594a9c: /* US_TAB */
		*ret = SDL_SCANCODE_TAB;
		return 1;
	case 0x8f059f54: /* US_SPACE */
		*ret = SDL_SCANCODE_SPACE;
		return 1;
	case 0x9ed4e919: /* US_MINUS */
		*ret = SDL_SCANCODE_MINUS;
		return 1;
	case 0xa93b1868: /* US_EQUALS */
		*ret = SDL_SCANCODE_EQUALS;
		return 1;
	case 0xb3be8582: /* US_LEFTBRACKET */
		*ret = SDL_SCANCODE_LEFTBRACKET;
		return 1;
	case 0x497ff155: /* US_RIGHTBRACKET */
		*ret = SDL_SCANCODE_RIGHTBRACKET;
		return 1;
	case 0x45d98376: /* US_BACKSLASH */
		*ret = SDL_SCANCODE_BACKSLASH;
		return 1;
	case 0x124652bf: /* US_SEMICOLON */
		*ret = SDL_SCANCODE_SEMICOLON;
		return 1;
	case 0x1ec9adfe: /* US_APOSTROPHE */
		*ret = SDL_SCANCODE_APOSTROPHE;
		return 1;
	case 0x87d98089: /* US_GRAVE */
		*ret = SDL_SCANCODE_GRAVE;
		return 1;
	case 0x776b5fec: /* US_COMMA */
		*ret = SDL_SCANCODE_COMMA;
		return 1;
	case 0x547a0507: /* US_PERIOD */
		*ret = SDL_SCANCODE_PERIOD;
		return 1;
	case 0xa1b9199f: /* US_SLASH */
		*ret = SDL_SCANCODE_SLASH;
		return 1;
	case 0x3babdcef: /* US_CAPSLOCK */
		*ret = SDL_SCANCODE_CAPSLOCK;
		return 1;
	case 0x4a296696: /* US_PRINTSCREEN */
		*ret = SDL_SCANCODE_PRINTSCREEN;
		return 1;
	case 0xdec946a5: /* US_SCROLLLOCK */
		*ret = SDL_SCANCODE_SCROLLLOCK;
		return 1;
	case 0x71edcc83: /* US_PAUSE */
		*ret = SDL_SCANCODE_PAUSE;
		return 1;
	case 0x540e853c: /* US_INSERT */
		*ret = SDL_SCANCODE_INSERT;
		return 1;
	case 0xabd0674e: /* US_DELETE */
		*ret = SDL_SCANCODE_DELETE;
		return 1;
	case 0xbadf0555: /* US_HOME */
		*ret = SDL_SCANCODE_HOME;
		return 1;
	case 0x68463a21: /* US_END */
		*ret = SDL_SCANCODE_END;
		return 1;
	case 0x65d0d3a8: /* US_PAGEUP */
		*ret = SDL_SCANCODE_PAGEUP;
		return 1;
	case 0xa39cb113: /* US_PAGEDOWN */
		*ret = SDL_SCANCODE_PAGEDOWN;
		return 1;
	case 0x12bd2b7a: /* US_RIGHT */
		*ret = SDL_SCANCODE_RIGHT;
		return 1;
	case 0xb16eeeed: /* US_LEFT */
		*ret = SDL_SCANCODE_LEFT;
		return 1;
	case 0xd7f699be: /* US_DOWN */
		*ret = SDL_SCANCODE_DOWN;
		return 1;
	case 0x242e8682: /* US_UP */
		*ret = SDL_SCANCODE_UP;
		return 1;
	case 0xa802bd76: /* US_NUMLOCKCLEAR */
		*ret = SDL_SCANCODE_NUMLOCKCLEAR;
		return 1;
	case 0x6896d1bc: /* US_KP_DIVIDE */
		*ret = SDL_SCANCODE_KP_DIVIDE;
		return 1;
	case 0xdb8db6df: /* US_KP_MULTIPLY */
		*ret = SDL_SCANCODE_KP_MULTIPLY;
		return 1;
	case 0x3e897c92: /* US_KP_MINUS */
		*ret = SDL_SCANCODE_KP_MINUS;
		return 1;
	case 0x0c8c1a94: /* US_KP_PLUS */
		*ret = SDL_SCANCODE_KP_PLUS;
		return 1;
	case 0xbf5a0b8b: /* US_KP_ENTER */
		*ret = SDL_SCANCODE_KP_ENTER;
		return 1;
	case 0x908c8b00: /* US_KP_1 */
		*ret = SDL_SCANCODE_KP_1;
		return 1;
	case 0x0985daba: /* US_KP_2 */
		*ret = SDL_SCANCODE_KP_2;
		return 1;
	case 0x7e82ea2c: /* US_KP_3 */
		*ret = SDL_SCANCODE_KP_3;
		return 1;
	case 0xe0e67f8f: /* US_KP_4 */
		*ret = SDL_SCANCODE_KP_4;
		return 1;
	case 0x97e14f19: /* US_KP_5 */
		*ret = SDL_SCANCODE_KP_5;
		return 1;
	case 0x0ee81ea3: /* US_KP_6 */
		*ret = SDL_SCANCODE_KP_6;
		return 1;
	case 0x79ef2e35: /* US_KP_7 */
		*ret = SDL_SCANCODE_KP_7;
		return 1;
	case 0xe95033a4: /* US_KP_8 */
		*ret = SDL_SCANCODE_KP_8;
		return 1;
	case 0x9e570332: /* US_KP_9 */
		*ret = SDL_SCANCODE_KP_9;
		return 1;
	case 0xe78bbb96: /* US_KP_0 */
		*ret = SDL_SCANCODE_KP_0;
		return 1;
	case 0x2eb0023a: /* US_KP_PERIOD */
		*ret = SDL_SCANCODE_KP_PERIOD;
		return 1;
	case 0xd3f11f55: /* US_KP_EQUALS */
		*ret = SDL_SCANCODE_KP_EQUALS;
		return 1;
	default:
		break;
	}

	*ret = SDL_SCANCODE_UNKNOWN;
	return 0;
}

int keybinds_parse_modkey(const char *name, SDL_Keymod *ret)
{
	switch (crc32b(name)) {
	case 0x34b79cce: /* CTRL */
		*ret = KMOD_CTRL;
		return 1;
	case 0x4ed20187: /* LCTRL */
		*ret = KMOD_LCTRL;
		return 1;
	case 0x91022864: /* RCTRL */
		*ret = KMOD_RCTRL;
		return 1;
	case 0x525ff9f5: /* SHIFT */
		*ret = KMOD_SHIFT;
		return 1;
	case 0x5d25655c: /* LSHIFT */
		*ret = KMOD_LSHIFT;
		return 1;
	case 0x64f906b7: /* RSHIFT */
		*ret = KMOD_RSHIFT;
		return 1;
	case 0xbed3ab01: /* ALT */
		*ret = KMOD_ALT;
		return 1;
	case 0xb1144a8a: /* LALT */
		*ret = KMOD_LALT;
		return 1;
	case 0x01d26a26: /* RALT */
		*ret = KMOD_RALT;
		return 1;
	default:
		break;
	}

	*ret = KMOD_NONE;
	return 0;
}

int keybinds_parse_keycode(const char *name, SDL_Keycode *ret)
{
	switch (crc32b(name)) {
	case 0x5766f889: /* RETURN */
		*ret = SDLK_RETURN;
		return 1;
	case 0xd5107708: /* ESCAPE */
		*ret = SDLK_ESCAPE;
		return 1;
	case 0xfb229c80: /* BACKSPACE */
		*ret = SDLK_BACKSPACE;
		return 1;
	case 0xe5440186: /* TAB */
		*ret = SDLK_TAB;
		return 1;
	case 0xde26038a: /* SPACE */
		*ret = SDLK_SPACE;
		return 1;
	case 0xfd9de4b0: /* EXCLAIM */
		*ret = SDLK_EXCLAIM;
		return 1;
	case 0xd8a296bc: /* QUOTEDBL */
		*ret = SDLK_QUOTEDBL;
		return 1;
	case 0xe72d8f0c: /* HASH */
		*ret = SDLK_HASH;
		return 1;
	case 0x5ef37e23: /* PERCENT */
		*ret = SDLK_PERCENT;
		return 1;
	case 0x3bedfbfc: /* DOLLAR */
		*ret = SDLK_DOLLAR;
		return 1;
	case 0x14409aac: /* AMPERSAND */
		*ret = SDLK_AMPERSAND;
		return 1;
	case 0x9c250944: /* QUOTE */
		*ret = SDLK_QUOTE;
		return 1;
	case 0x67ffff0c: /* LEFTPAREN */
		*ret = SDLK_LEFTPAREN;
		return 1;
	case 0x8710ecce: /* RIGHTPAREN */
		*ret = SDLK_RIGHTPAREN;
		return 1;
	case 0xfbf39401: /* ASTERISK */
		*ret = SDLK_ASTERISK;
		return 1;
	case 0xa6670d45: /* PLUS */
		*ret = SDLK_PLUS;
		return 1;
	case 0x2648c332: /* COMMA */
		*ret = SDLK_COMMA;
		return 1;
	case 0xcff775c7: /* MINUS */
		*ret = SDLK_MINUS;
		return 1;
	case 0x3540d948: /* PERIOD */
		*ret = SDLK_PERIOD;
		return 1;
	case 0xf09a8541: /* SLASH */
		*ret = SDLK_SLASH;
		return 1;
	case 0xf4dbdf21: /* 0 */
		*ret = SDLK_0;
		return 1;
	case 0x83dcefb7: /* 1 */
		*ret = SDLK_1;
		return 1;
	case 0x1ad5be0d: /* 2 */
		*ret = SDLK_2;
		return 1;
	case 0x6dd28e9b: /* 3 */
		*ret = SDLK_3;
		return 1;
	case 0xf3b61b38: /* 4 */
		*ret = SDLK_4;
		return 1;
	case 0x84b12bae: /* 5 */
		*ret = SDLK_5;
		return 1;
	case 0x1db87a14: /* 6 */
		*ret = SDLK_6;
		return 1;
	case 0x6abf4a82: /* 7 */
		*ret = SDLK_7;
		return 1;
	case 0xfa005713: /* 8 */
		*ret = SDLK_8;
		return 1;
	case 0x8d076785: /* 9 */
		*ret = SDLK_9;
		return 1;
	case 0x8503d616: /* COLON */
		*ret = SDLK_COLON;
		return 1;
	case 0x8201cb82: /* SEMICOLON */
		*ret = SDLK_SEMICOLON;
		return 1;
	case 0xe523796b: /* LESS */
		*ret = SDLK_LESS;
		return 1;
	case 0xc801c427: /* EQUALS */
		*ret = SDLK_EQUALS;
		return 1;
	case 0x8de3d8e0: /* GREATER */
		*ret = SDLK_GREATER;
		return 1;
	case 0x70c4d502: /* QUESTION */
		*ret = SDLK_QUESTION;
		return 1;
	case 0xc4bdf956: /* AT */
		*ret = SDLK_AT;
		return 1;
	case 0x5085769b: /* LEFTBRACKET */
		*ret = SDLK_LEFTBRACKET;
		return 1;
	case 0xd59e1a4b: /* BACKSLASH */
		*ret = SDLK_BACKSLASH;
		return 1;
	case 0x2df76266: /* RIGHTBRACKET */
		*ret = SDLK_RIGHTBRACKET;
		return 1;
	case 0x74e93eaf: /* CARET */
		*ret = SDLK_CARET;
		return 1;
	case 0x53aac026: /* UNDERSCORE */
		*ret = SDLK_UNDERSCORE;
		return 1;
	case 0xb921964e: /* BACKQUOTE */
		*ret = SDLK_BACKQUOTE;
		return 1;
	case 0xe8b7be43: /* a */
		*ret = SDLK_a;
		return 1;
	case 0x71beeff9: /* b */
		*ret = SDLK_b;
		return 1;
	case 0x06b9df6f: /* c */
		*ret = SDLK_c;
		return 1;
	case 0x98dd4acc: /* d */
		*ret = SDLK_d;
		return 1;
	case 0xefda7a5a: /* e */
		*ret = SDLK_e;
		return 1;
	case 0x76d32be0: /* f */
		*ret = SDLK_f;
		return 1;
	case 0x01d41b76: /* g */
		*ret = SDLK_g;
		return 1;
	case 0x916b06e7: /* h */
		*ret = SDLK_h;
		return 1;
	case 0xe66c3671: /* i */
		*ret = SDLK_i;
		return 1;
	case 0x7f6567cb: /* j */
		*ret = SDLK_j;
		return 1;
	case 0x0862575d: /* k */
		*ret = SDLK_k;
		return 1;
	case 0x9606c2fe: /* l */
		*ret = SDLK_l;
		return 1;
	case 0xe101f268: /* m */
		*ret = SDLK_m;
		return 1;
	case 0x7808a3d2: /* n */
		*ret = SDLK_n;
		return 1;
	case 0x0f0f9344: /* o */
		*ret = SDLK_o;
		return 1;
	case 0x82079eb1: /* p */
		*ret = SDLK_p;
		return 1;
	case 0xf500ae27: /* q */
		*ret = SDLK_q;
		return 1;
	case 0x6c09ff9d: /* r */
		*ret = SDLK_r;
		return 1;
	case 0x1b0ecf0b: /* s */
		*ret = SDLK_s;
		return 1;
	case 0x856a5aa8: /* t */
		*ret = SDLK_t;
		return 1;
	case 0xf26d6a3e: /* u */
		*ret = SDLK_u;
		return 1;
	case 0x6b643b84: /* v */
		*ret = SDLK_v;
		return 1;
	case 0x1c630b12: /* w */
		*ret = SDLK_w;
		return 1;
	case 0x8cdc1683: /* x */
		*ret = SDLK_x;
		return 1;
	case 0xfbdb2615: /* y */
		*ret = SDLK_y;
		return 1;
	case 0x62d277af: /* z */
		*ret = SDLK_z;
		return 1;
	case 0xc32f70e0: /* CAPSLOCK */
		*ret = SDLK_CAPSLOCK;
		return 1;
	case 0xb624fa46: /* F1 */
		*ret = SDLK_F1;
		return 1;
	case 0x2f2dabfc: /* F2 */
		*ret = SDLK_F2;
		return 1;
	case 0x582a9b6a: /* F3 */
		*ret = SDLK_F3;
		return 1;
	case 0xc64e0ec9: /* F4 */
		*ret = SDLK_F4;
		return 1;
	case 0xb1493e5f: /* F5 */
		*ret = SDLK_F5;
		return 1;
	case 0x28406fe5: /* F6 */
		*ret = SDLK_F6;
		return 1;
	case 0x5f475f73: /* F7 */
		*ret = SDLK_F7;
		return 1;
	case 0xcff842e2: /* F8 */
		*ret = SDLK_F8;
		return 1;
	case 0xb8ff7274: /* F9 */
		*ret = SDLK_F9;
		return 1;
	case 0x6bd21f7e: /* F10 */
		*ret = SDLK_F10;
		return 1;
	case 0x1cd52fe8: /* F11 */
		*ret = SDLK_F11;
		return 1;
	case 0x85dc7e52: /* F12 */
		*ret = SDLK_F12;
		return 1;
	case 0xa912958f: /* PRINTSCREEN */
		*ret = SDLK_PRINTSCREEN;
		return 1;
	case 0x86314d2d: /* SCROLLLOCK */
		*ret = SDLK_SCROLLLOCK;
		return 1;
	case 0x20ce505d: /* PAUSE */
		*ret = SDLK_PAUSE;
		return 1;
	case 0x35345973: /* INSERT */
		*ret = SDLK_INSERT;
		return 1;
	case 0x4743e164: /* HOME */
		*ret = SDLK_HOME;
		return 1;
	case 0x04ea0fe7: /* PAGEUP */
		*ret = SDLK_PAGEUP;
		return 1;
	case 0xcaeabb01: /* DELETE */
		*ret = SDLK_DELETE;
		return 1;
	case 0x965b713b: /* END */
		*ret = SDLK_END;
		return 1;
	case 0x5b181d1c: /* PAGEDOWN */
		*ret = SDLK_PAGEDOWN;
		return 1;
	case 0x439eb7a4: /* RIGHT */
		*ret = SDLK_RIGHT;
		return 1;
	case 0x4cf20adc: /* LEFT */
		*ret = SDLK_LEFT;
		return 1;
	case 0x2a6a7d8f: /* DOWN */
		*ret = SDLK_DOWN;
		return 1;
	case 0xed7eea1a: /* UP */
		*ret = SDLK_UP;
		return 1;
	case 0xcc8a2e45: /* NUMLOCKCLEAR */
		*ret = SDLK_NUMLOCKCLEAR;
		return 1;
	case 0xf8d14881: /* KP_DIVIDE */
		*ret = SDLK_KP_DIVIDE;
		return 1;
	case 0x38b645c6: /* KP_MULTIPLY */
		*ret = SDLK_KP_MULTIPLY;
		return 1;
	case 0xc60dd09d: /* KP_MINUS */
		*ret = SDLK_KP_MINUS;
		return 1;
	case 0xea8e7c49: /* KP_PLUS */
		*ret = SDLK_KP_PLUS;
		return 1;
	case 0x47dea784: /* KP_ENTER */
		*ret = SDLK_KP_ENTER;
		return 1;
	case 0x6d106f31: /* KP_1 */
		*ret = SDLK_KP_1;
		return 1;
	case 0xf4193e8b: /* KP_2 */
		*ret = SDLK_KP_2;
		return 1;
	case 0x831e0e1d: /* KP_3 */
		*ret = SDLK_KP_3;
		return 1;
	case 0x1d7a9bbe: /* KP_4 */
		*ret = SDLK_KP_4;
		return 1;
	case 0x6a7dab28: /* KP_5 */
		*ret = SDLK_KP_5;
		return 1;
	case 0xf374fa92: /* KP_6 */
		*ret = SDLK_KP_6;
		return 1;
	case 0x8473ca04: /* KP_7 */
		*ret = SDLK_KP_7;
		return 1;
	case 0x14ccd795: /* KP_8 */
		*ret = SDLK_KP_8;
		return 1;
	case 0x63cbe703: /* KP_9 */
		*ret = SDLK_KP_9;
		return 1;
	case 0x1a175fa7: /* KP_0 */
		*ret = SDLK_KP_0;
		return 1;
	case 0xbef79b07: /* KP_PERIOD */
		*ret = SDLK_KP_PERIOD;
		return 1;
	case 0x29584f29: /* APPLICATION */
		*ret = SDLK_APPLICATION;
		return 1;
	case 0x5cdec310: /* POWER */
		*ret = SDLK_POWER;
		return 1;
	case 0x43b68668: /* KP_EQUALS */
		*ret = SDLK_KP_EQUALS;
		return 1;
	case 0xf2db4ec4: /* F13 */
		*ret = SDLK_F13;
		return 1;
	case 0x6cbfdb67: /* F14 */
		*ret = SDLK_F14;
		return 1;
	case 0x1bb8ebf1: /* F15 */
		*ret = SDLK_F15;
		return 1;
	case 0x82b1ba4b: /* F16 */
		*ret = SDLK_F16;
		return 1;
	case 0xf5b68add: /* F17 */
		*ret = SDLK_F17;
		return 1;
	case 0x6509974c: /* F18 */
		*ret = SDLK_F18;
		return 1;
	case 0x120ea7da: /* F19 */
		*ret = SDLK_F19;
		return 1;
	case 0x40ff4cbd: /* F20 */
		*ret = SDLK_F20;
		return 1;
	case 0x37f87c2b: /* F21 */
		*ret = SDLK_F21;
		return 1;
	case 0xaef12d91: /* F22 */
		*ret = SDLK_F22;
		return 1;
	case 0xd9f61d07: /* F23 */
		*ret = SDLK_F23;
		return 1;
	case 0x479288a4: /* F24 */
		*ret = SDLK_F24;
		return 1;
	case 0xc026eec4: /* EXECUTE */
		*ret = SDLK_EXECUTE;
		return 1;
	case 0x3e12b118: /* HELP */
		*ret = SDLK_HELP;
		return 1;
	case 0x4b90d727: /* MENU */
		*ret = SDLK_MENU;
		return 1;
	case 0xbb0a2d46: /* SELECT */
		*ret = SDLK_SELECT;
		return 1;
	case 0x8fc3fb02: /* STOP */
		*ret = SDLK_STOP;
		return 1;
	case 0x64f5994c: /* AGAIN */
		*ret = SDLK_AGAIN;
		return 1;
	case 0xd5e55646: /* UNDO */
		*ret = SDLK_UNDO;
		return 1;
	case 0x2657d677: /* CUT */
		*ret = SDLK_CUT;
		return 1;
	case 0x7b2f5636: /* COPY */
		*ret = SDLK_COPY;
		return 1;
	case 0x6b02ba28: /* PASTE */
		*ret = SDLK_PASTE;
		return 1;
	case 0xff3b89b0: /* FIND */
		*ret = SDLK_FIND;
		return 1;
	case 0xfa2c9ee8: /* MUTE */
		*ret = SDLK_MUTE;
		return 1;
	case 0x7fc99d3a: /* VOLUMEUP */
		*ret = SDLK_VOLUMEUP;
		return 1;
	case 0x718f2f05: /* VOLUMEDOWN */
		*ret = SDLK_VOLUMEDOWN;
		return 1;
	case 0x2fb26668: /* KP_COMMA */
		*ret = SDLK_KP_COMMA;
		return 1;
	case 0xdb0326b4: /* KP_EQUALSAS400 */
		*ret = SDLK_KP_EQUALSAS400;
		return 1;
	case 0x83ce0499: /* ALTERASE */
		*ret = SDLK_ALTERASE;
		return 1;
	case 0x2939f6f0: /* SYSREQ */
		*ret = SDLK_SYSREQ;
		return 1;
	case 0xa6ee02f4: /* CANCEL */
		*ret = SDLK_CANCEL;
		return 1;
	case 0x12e533b6: /* CLEAR */
		*ret = SDLK_CLEAR;
		return 1;
	case 0x12fa2aa2: /* PRIOR */
		*ret = SDLK_PRIOR;
		return 1;
	case 0x8ee6e371: /* RETURN2 */
		*ret = SDLK_RETURN2;
		return 1;
	case 0xd330d367: /* SEPARATOR */
		*ret = SDLK_SEPARATOR;
		return 1;
	case 0x2f4d2f13: /* OUT */
		*ret = SDLK_OUT;
		return 1;
	case 0x86e4325f: /* OPER */
		*ret = SDLK_OPER;
		return 1;
	case 0xce31512f: /* CLEARAGAIN */
		*ret = SDLK_CLEARAGAIN;
		return 1;
	case 0x24eb34bf: /* CRSEL */
		*ret = SDLK_CRSEL;
		return 1;
	case 0xc416217b: /* EXSEL */
		*ret = SDLK_EXSEL;
		return 1;
	case 0xbc73fe35: /* KP_00 */
		*ret = SDLK_KP_00;
		return 1;
	case 0xa2d468fc: /* KP_000 */
		*ret = SDLK_KP_000;
		return 1;
	case 0xbde98749: /* THOUSANDSSEPARATOR */
		*ret = SDLK_THOUSANDSSEPARATOR;
		return 1;
	case 0xe0fd2d61: /* DECIMALSEPARATOR */
		*ret = SDLK_DECIMALSEPARATOR;
		return 1;
	case 0xd668c4a2: /* CURRENCYUNIT */
		*ret = SDLK_CURRENCYUNIT;
		return 1;
	case 0x3b56fb97: /* CURRENCYSUBUNIT */
		*ret = SDLK_CURRENCYSUBUNIT;
		return 1;
	case 0x8b733ed2: /* KP_LEFTPAREN */
		*ret = SDLK_KP_LEFTPAREN;
		return 1;
	case 0xe6979fdc: /* KP_RIGHTPAREN */
		*ret = SDLK_KP_RIGHTPAREN;
		return 1;
	case 0x0c176166: /* KP_LEFTBRACE */
		*ret = SDLK_KP_LEFTBRACE;
		return 1;
	case 0x61f3c068: /* KP_RIGHTBRACE */
		*ret = SDLK_KP_RIGHTBRACE;
		return 1;
	case 0x652553a7: /* KP_TAB */
		*ret = SDLK_KP_TAB;
		return 1;
	case 0x17ae5d5e: /* KP_BACKSPACE */
		*ret = SDLK_KP_BACKSPACE;
		return 1;
	case 0x3d151e0d: /* KP_A */
		*ret = SDLK_KP_A;
		return 1;
	case 0xa41c4fb7: /* KP_B */
		*ret = SDLK_KP_B;
		return 1;
	case 0xd31b7f21: /* KP_C */
		*ret = SDLK_KP_C;
		return 1;
	case 0x4d7fea82: /* KP_D */
		*ret = SDLK_KP_D;
		return 1;
	case 0x3a78da14: /* KP_E */
		*ret = SDLK_KP_E;
		return 1;
	case 0xa3718bae: /* KP_F */
		*ret = SDLK_KP_F;
		return 1;
	case 0xef0b9729: /* KP_XOR */
		*ret = SDLK_KP_XOR;
		return 1;
	case 0x5524664a: /* KP_POWER */
		*ret = SDLK_KP_POWER;
		return 1;
	case 0xb81b9560: /* KP_PERCENT */
		*ret = SDLK_KP_PERCENT;
		return 1;
	case 0xa9ca0867: /* KP_LESS */
		*ret = SDLK_KP_LESS;
		return 1;
	case 0x6b0b33a3: /* KP_GREATER */
		*ret = SDLK_KP_GREATER;
		return 1;
	case 0xf8cc5b72: /* KP_AMPERSAND */
		*ret = SDLK_KP_AMPERSAND;
		return 1;
	case 0x01a3b230: /* KP_DBLAMPERSAND */
		*ret = SDLK_KP_DBLAMPERSAND;
		return 1;
	case 0x0e18c1be: /* KP_VERTICALBAR */
		*ret = SDLK_KP_VERTICALBAR;
		return 1;
	case 0x15814f8a: /* KP_DBLVERTICALBAR */
		*ret = SDLK_KP_DBLVERTICALBAR;
		return 1;
	case 0x8cf9734c: /* KP_COLON */
		*ret = SDLK_KP_COLON;
		return 1;
	case 0xabc4fe00: /* KP_HASH */
		*ret = SDLK_KP_HASH;
		return 1;
	case 0xd7dca6d0: /* KP_SPACE */
		*ret = SDLK_KP_SPACE;
		return 1;
	case 0xc08813c3: /* KP_AT */
		*ret = SDLK_KP_AT;
		return 1;
	case 0x7cad3c27: /* KP_EXCLAM */
		*ret = SDLK_KP_EXCLAM;
		return 1;
	case 0x535dde22: /* KP_MEMSTORE */
		*ret = SDLK_KP_MEMSTORE;
		return 1;
	case 0x6bf38a43: /* KP_MEMRECALL */
		*ret = SDLK_KP_MEMRECALL;
		return 1;
	case 0x49bb7753: /* KP_MEMCLEAR */
		*ret = SDLK_KP_MEMCLEAR;
		return 1;
	case 0xe42245f8: /* KP_MEMADD */
		*ret = SDLK_KP_MEMADD;
		return 1;
	case 0x50846227: /* KP_MEMSUBTRACT */
		*ret = SDLK_KP_MEMSUBTRACT;
		return 1;
	case 0x606a59e5: /* KP_MEMMULTIPLY */
		*ret = SDLK_KP_MEMMULTIPLY;
		return 1;
	case 0xa35d427d: /* KP_MEMDIVIDE */
		*ret = SDLK_KP_MEMDIVIDE;
		return 1;
	case 0xf4c77d37: /* KP_PLUSMINUS */
		*ret = SDLK_KP_PLUSMINUS;
		return 1;
	case 0x1b1f96ec: /* KP_CLEAR */
		*ret = SDLK_KP_CLEAR;
		return 1;
	case 0x1736e4b1: /* KP_CLEARENTRY */
		*ret = SDLK_KP_CLEARENTRY;
		return 1;
	case 0xbdaf6ccc: /* KP_BINARY */
		*ret = SDLK_KP_BINARY;
		return 1;
	case 0x61679f9f: /* KP_OCTAL */
		*ret = SDLK_KP_OCTAL;
		return 1;
	case 0x8350a6ca: /* KP_DECIMAL */
		*ret = SDLK_KP_DECIMAL;
		return 1;
	case 0x582ec073: /* KP_HEXADECIMAL */
		*ret = SDLK_KP_HEXADECIMAL;
		return 1;
	case 0xfd59d355: /* RGUI */
		*ret = SDLK_RGUI;
		return 1;
	case 0xa15faa1f: /* MODE */
		*ret = SDLK_MODE;
		return 1;
	case 0x6368198a: /* AUDIONEXT */
		*ret = SDLK_AUDIONEXT;
		return 1;
	case 0xdba581e3: /* AUDIOPREV */
		*ret = SDLK_AUDIOPREV;
		return 1;
	case 0xde111f00: /* AUDIOSTOP */
		*ret = SDLK_AUDIOSTOP;
		return 1;
	case 0x39ced70c: /* AUDIOPLAY */
		*ret = SDLK_AUDIOPLAY;
		return 1;
	case 0xabfe7aea: /* AUDIOMUTE */
		*ret = SDLK_AUDIOMUTE;
		return 1;
	case 0x53d05005: /* MEDIASELECT */
		*ret = SDLK_MEDIASELECT;
		return 1;
	case 0x9647eee3: /* WWW */
		*ret = SDLK_WWW;
		return 1;
	case 0x67b341fc: /* MAIL */
		*ret = SDLK_MAIL;
		return 1;
	case 0x2fe68dfd: /* CALCULATOR */
		*ret = SDLK_CALCULATOR;
		return 1;
	case 0x64ab3bea: /* COMPUTER */
		*ret = SDLK_COMPUTER;
		return 1;
	case 0xa8a5e238: /* AC_SEARCH */
		*ret = SDLK_AC_SEARCH;
		return 1;
	case 0x2a98bf13: /* AC_HOME */
		*ret = SDLK_AC_HOME;
		return 1;
	case 0x368072f4: /* AC_BACK */
		*ret = SDLK_AC_BACK;
		return 1;
	case 0xbc53d4a2: /* AC_FORWARD */
		*ret = SDLK_AC_FORWARD;
		return 1;
	case 0xe218a575: /* AC_STOP */
		*ret = SDLK_AC_STOP;
		return 1;
	case 0x3b435bdf: /* AC_REFRESH */
		*ret = SDLK_AC_REFRESH;
		return 1;
	case 0x0dbf54da: /* AC_BOOKMARKS */
		*ret = SDLK_AC_BOOKMARKS;
		return 1;
	case 0x3c73f952: /* BRIGHTNESSDOWN */
		*ret = SDLK_BRIGHTNESSDOWN;
		return 1;
	case 0xcc45a9d8: /* BRIGHTNESSUP */
		*ret = SDLK_BRIGHTNESSUP;
		return 1;
	case 0xc2cdbe8a: /* DISPLAYSWITCH */
		*ret = SDLK_DISPLAYSWITCH;
		return 1;
	case 0x7c610f56: /* KBDILLUMTOGGLE */
		*ret = SDLK_KBDILLUMTOGGLE;
		return 1;
	case 0x5bf708b9: /* KBDILLUMDOWN */
		*ret = SDLK_KBDILLUMDOWN;
		return 1;
	case 0xc45f25a4: /* KBDILLUMUP */
		*ret = SDLK_KBDILLUMUP;
		return 1;
	case 0x639b5e7d: /* EJECT */
		*ret = SDLK_EJECT;
		return 1;
	case 0xf867001c: /* SLEEP */
		*ret = SDLK_SLEEP;
		return 1;
	case 0x8535939a: /* APP1 */
		*ret = SDLK_APP1;
		return 1;
	case 0x1c3cc220: /* APP2 */
		*ret = SDLK_APP2;
		return 1;
	case 0xc31cac01: /* AUDIOREWIND */
		*ret = SDLK_AUDIOREWIND;
		return 1;
	case 0x61c78cf0: /* AUDIOFASTFORWARD */
		*ret = SDLK_AUDIOFASTFORWARD;
		return 1;
	case 0x75ec7b66: /* SOFTLEFT */
		*ret = SDLK_SOFTLEFT;
		return 1;
	case 0x6813f347: /* SOFTRIGHT */
		*ret = SDLK_SOFTRIGHT;
		return 1;
	case 0xfa1bc28a: /* CALL */
		*ret = SDLK_CALL;
		return 1;
	case 0xc8210da3: /* ENDCALL */
		*ret = SDLK_ENDCALL;
		return 1;
	default:
		break;
	}

	*ret = SDLK_UNKNOWN;
	return 0;
}

